import assert from "node:assert/strict";
import { readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { strFromU8, unzipSync } from "fflate";
import { createManuscriptDocx } from "../src/docx";
import { CompilePreparationService } from "../src/compile-preparation";
import { createDefaultProfiles } from "../src/profiles";
import { loadFixtureTree } from "./fixture-loader";
import { validateDocxBytes } from "../src/docx-validator";
import { SafeBinaryWriter, type SafeBinaryBackend } from "../src/safe-binary-writer";

const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence");
const profile = createDefaultProfiles()[1]; profile.useParts = true; profile.chapterSource = "folders"; profile.sceneSeparator = "#"; profile.partDisplay = "word-title"; profile.chapterDisplay = "word-title"; profile.bodySectionAliases = ["Scene", "Manuscript", "Text", "Draft", "Body"];
const session = await new CompilePreparationService(loaded.vault as never, profile, 250).prepareAuthoritative({ manuscriptRoot: loaded.root.path, profile, structurePreset: "novel-parts", purpose: "compile", route: "legacy-profile" });
const { book } = session;
const bytes = createManuscriptDocx(book, profile, { title: "Warden of Silence", author: "Anthony Fitzpatrick", titlePage: true, font: "Times New Roman", fontSize: 12, lineSpacing: 2, firstLineIndent: 0.5, partDisplay: "word-title", chapterDisplay: "word-title" });
assert.equal(validateDocxBytes(bytes).valid, true);
const backend: SafeBinaryBackend = { kind: "filesystem", exists: async (value) => { try { await stat(value); return true; } catch { return false; } }, read: async (value) => new Uint8Array(await readFile(value)), write: async (value, data) => { await writeFile(value, data); }, rename: async (from, to) => { await rename(from, to); }, remove: async (value) => { await rm(value, { force: true }); }, list: async (folder) => (await readdir(folder)).map((name) => ({ path: path.join(folder, name), mtime: 0 })) };
const stages: string[] = []; const outputPath = ".test-build/Warden-of-Silence-regression.docx"; const saved = await new SafeBinaryWriter(backend).writeValidated(outputPath, bytes, { token: "docx-integration", onProgress: (stage) => stages.push(stage) });
assert.equal(saved.finalValidation.valid, true); assert.ok(stages.includes("Verifying temporary file")); assert.ok(stages.includes("Verifying saved DOCX"));
const finalBytes = new Uint8Array(await readFile(outputPath)); assert.equal(validateDocxBytes(finalBytes).valid, true); assert.deepEqual(finalBytes, bytes);
assert.equal((await readdir(".test-build")).some((name) => /Warden-of-Silence-regression\.docx\.manuscript-compiler-.*\.(?:tmp|backup)$/.test(name)), false);
assert.equal(String.fromCharCode(...bytes.slice(0, 2)), "PK");
const entries = unzipSync(bytes); for (const required of ["[Content_Types].xml", "_rels/.rels", "word/document.xml", "word/styles.xml", "docProps/core.xml"]) assert.ok(entries[required], `Missing ${required}`);
const document = strFromU8(entries["word/document.xml"]); const styles = strFromU8(entries["word/styles.xml"]); const core = strFromU8(entries["docProps/core.xml"]);
for (const style of ["Title", "Subtitle", "Author", "PartNumber", "PartTitle", "ChapterNumber", "ChapterTitle", "BodyText", "FirstParagraph", "SceneBreak", "FrontMatterHeading", "BackMatterHeading"]) assert.match(styles, new RegExp(`w:styleId="${style}"`), `Missing ${style}`);
assert.match(styles, /w:styleId="PartNumber"[\s\S]*?w:pageBreakBefore/); assert.match(styles, /w:styleId="ChapterNumber"[\s\S]*?w:pageBreakBefore/);
assert.match(document, /w:pStyle w:val="Title"[\s\S]*?Warden of Silence/); assert.match(document, /w:pStyle w:val="Author"[\s\S]*?Anthony Fitzpatrick/);
assert.match(document, /w:pStyle w:val="PartNumber"[\s\S]*?Part One/); assert.match(document, /w:pStyle w:val="PartTitle"[\s\S]*?The Silence Breaks/);
assert.match(document, /w:pStyle w:val="ChapterNumber"[\s\S]*?Chapter One/); assert.match(document, /w:pStyle w:val="ChapterTitle"[\s\S]*?The Silence of Östersund/);
assert.match(document, /w:pStyle w:val="SceneBreak"[\s\S]*?\* \* \*/); assert.match(document, /w:pStyle w:val="FirstParagraph"[\s\S]*?Östersund was silent/); assert.match(document, /w:pStyle w:val="BodyText"[\s\S]*?The barn answered/);
assert.match(document, /winter stars—too silent/); assert.match(document, /“Listen,”/); assert.match(document, /Östersund/);
for (const forbidden of ["Part: Archive", "Part: Development", "Part: Exports", "Part 0: Manuscript", "Chapter 0: Book 1 - Warden of Silence", "Warden of Silence Dashboard", "The Watchers of Silence Series Dashboard", "Revision Notes", "Internal synopsis", "Editing Status", "Character Notes", "Previous Export"]) assert.doesNotMatch(document, new RegExp(forbidden.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"), forbidden);
assert.ok(document.indexOf("Copyright ©") < document.indexOf("Part One")); assert.ok(document.indexOf("Part Two") < document.indexOf("With gratitude"));
assert.match(core, /Warden of Silence/);
process.stdout.write(`Built-in Warden regression DOCX passed (${bytes.length.toLocaleString()} bytes); wrote .test-build/Warden-of-Silence-regression.docx.\n`);
