import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import type { ScannedBook, ScannedChapter, ScannedPart } from "../src/types";

interface FixtureFile { path: string; name: string; basename: string; extension: string; absolutePath: string; }
interface FixtureFolder { path: string; name: string; }
const frontNames = new Set(["front matter", "ebook front matter", "print front matter"]); const backNames = new Set(["back matter", "ebook back matter", "print back matter"]);
const natural = new Intl.Collator(undefined, { numeric: true, sensitivity: "base" });
export async function loadFixtureScan(rootPath: string): Promise<{ scan: ScannedBook; vault: { cachedRead(file: FixtureFile): Promise<string> } }> {
  const rootAbsolute = path.resolve(rootPath); const root = folder(rootAbsolute, rootAbsolute); const entries = await visibleEntries(rootAbsolute); const folders = entries.filter((entry) => entry.isDirectory()); const front = folders.filter((entry) => frontNames.has(entry.name.toLowerCase())); const back = folders.filter((entry) => backNames.has(entry.name.toLowerCase())); const structural = folders.filter((entry) => !front.includes(entry) && !back.includes(entry));
  const frontMatter = (await Promise.all(front.map((entry) => collectMarkdown(rootAbsolute, path.join(rootAbsolute, entry.name))))).flat(); const backMatter = (await Promise.all(back.map((entry) => collectMarkdown(rootAbsolute, path.join(rootAbsolute, entry.name))))).flat(); const parts = await Promise.all(structural.map((entry) => scanPart(rootAbsolute, path.join(rootAbsolute, entry.name)))); const looseScenes = entries.filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".md")).map((entry) => file(rootAbsolute, path.join(rootAbsolute, entry.name)));
  const allMarkdown = [...frontMatter, ...parts.flatMap((part) => [...part.looseScenes, ...part.chapters.flatMap((chapter) => chapter.scenes)]), ...looseScenes, ...backMatter] as never[];
  return { scan: { root: root as never, frontMatter: frontMatter as never, parts, looseScenes: looseScenes as never, backMatter: backMatter as never, allMarkdown, warnings: [] }, vault: { cachedRead: async (item) => readFile(item.absolutePath, "utf8") } };
}
async function scanPart(root: string, absolute: string): Promise<ScannedPart> { const entries = await visibleEntries(absolute); const looseScenes = entries.filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".md")).map((entry) => file(root, path.join(absolute, entry.name))); const chapters: ScannedChapter[] = await Promise.all(entries.filter((entry) => entry.isDirectory()).map(async (entry) => ({ folder: folder(root, path.join(absolute, entry.name)) as never, scenes: await collectMarkdown(root, path.join(absolute, entry.name)) as never }))); return { folder: folder(root, absolute) as never, looseScenes: looseScenes as never, chapters }; }
async function collectMarkdown(root: string, absolute: string): Promise<FixtureFile[]> { const result: FixtureFile[] = []; for (const entry of await visibleEntries(absolute)) { const child = path.join(absolute, entry.name); if (entry.isDirectory()) result.push(...await collectMarkdown(root, child)); else if (entry.name.toLowerCase().endsWith(".md")) result.push(file(root, child)); } return result; }
async function visibleEntries(absolute: string) { return (await readdir(absolute, { withFileTypes: true })).filter((entry) => !entry.name.startsWith(".") && !entry.name.startsWith("Icon")).sort((a, b) => natural.compare(a.name, b.name)); }
function file(root: string, absolute: string): FixtureFile { const name = path.basename(absolute); return { path: path.relative(root, absolute).split(path.sep).join("/"), name, basename: name.replace(/\.md$/i, ""), extension: "md", absolutePath: absolute }; }
function folder(root: string, absolute: string): FixtureFolder { return { path: path.relative(root, absolute).split(path.sep).join("/") || path.basename(absolute), name: path.basename(absolute) }; }
