import assert from "node:assert/strict";
import { cleanManuscriptContent, ContentCleaningPipeline, removeCallouts, removeDataviewBlocks, removeHtmlComments, removeObsidianComments, removeProjectMetadataRegions, stripInternalLinks, stripYamlFrontmatter } from "../src/filters";
import { MarkdownGenerator } from "../src/markdown-generator";
import { MetadataFilterEngine } from "../src/metadata-filter";
import type { Book, ManuscriptDocument } from "../src/model";
import { extractNumber, sortDocuments, titleName } from "../src/ordering";
import { ManuscriptParser, mapConcurrent } from "../src/parser";
import { createDefaultProfiles } from "../src/profiles";
import { StatisticsEngine } from "../src/statistics";
import { TemplateEngine } from "../src/template-engine";
import { WarningEngine } from "../src/warnings";
import { ManuscriptValidationService } from "../src/validation";
import { DiagnosticsReportGenerator } from "../src/diagnostics";
import { DEFAULT_SETTINGS } from "../src/settings";
import { repairSettings } from "../src/profiles";
import { profileFromWizard } from "../src/wizards";
import { loadFixtureScan, loadFixtureTree } from "./fixture-loader";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { TFile, TFolder } from "obsidian";
import { VaultScanner } from "../src/vault-scanner";
import { MarkdownExporter, validateVaultPath } from "../src/exporter";
import { CompilationCancelledError } from "../src/cancellation";
import { DOCX_FORMATTING_PRESETS, docxFormattingForPreset, inferStructurePreset, resolveSimpleCompileRequest, validateSimpleCompileRequest } from "../src/simple-workflow";
import type { SimpleCompileRequest } from "../src/simple-workflow";
import { canProceedWithExport } from "../src/export-safety";
import { applyContentPlan, classifyContentPlan, createContentPlan } from "../src/content-plan";
import { calculateSourceFingerprint, compileInputSignature, CompilePreparationService, createPreparedExportRequest, preparedSessionMatchesInputs, sessionMatchesBook } from "../src/compile-preparation";
import { createManuscriptDocx } from "../src/docx";
import { strFromU8, unzipSync } from "fflate";
import { COMMAND_IDS } from "../src/commands";
import { BookRootResolver } from "../src/book-root-resolver";
import { CompileWorkspaceController } from "../src/workspace/compile-workspace-controller";
import { buildExportPreviewViewModel } from "../src/workspace/export-preview";
import { isEffectivelyIncluded, moveSibling, setItemIncluded } from "../src/workspace/content-tree";
import { OperationStateController } from "../src/operation-state";
import { CompileHistoryService } from "../src/compile-history";
import { ResultActionService } from "../src/result-actions";
import { createTestDocx } from "./docx-test-fixture";

const tests: Array<[string, () => void | Promise<void>]> = [];
const test = (name: string, action: () => void | Promise<void>): void => { tests.push([name, action]); };
async function sourceFiles(folder: string): Promise<string[]> { const entries = await readdir(folder, { withFileTypes: true }); const nested = await Promise.all(entries.map((entry) => entry.isDirectory() ? sourceFiles(path.join(folder, entry.name)) : Promise.resolve(entry.name.endsWith(".ts") ? [path.join(folder, entry.name)] : []))); return nested.flat(); }
const file = (name: string, content: string, metadata: Record<string, unknown> = {}): ManuscriptDocument => ({ file: { name: `${name}.md`, basename: name, path: `Book/${name}.md` } as never, title: name, number: extractNumber(name), metadata: { values: metadata }, rawContent: content, content, excluded: false });
const preparedRequest = (root: string, plan: ReturnType<typeof createContentPlan>): SimpleCompileRequest => ({ manuscriptRoot: root, structurePreset: "novel-parts", includeFrontMatter: true, includeBackMatter: true, exportFolder: "Manuscript Exports", outputFilename: "Warden of Silence.docx", outputFormat: "docx", docxPreset: "vellum", contentPlan: plan, formatting: { font: "Times New Roman", fontSize: 12, lineSpacing: 2, firstLineIndent: 0.5, pageSize: "letter", chapterPageBreak: true, titlePage: true }, tableOfContents: false, partDisplay: "word-title", chapterDisplay: "word-title", custom: { variables: { BookTitle: "Warden of Silence", Author: "Anthony Fitzpatrick" }, bodySectionAliases: ["Scene", "Manuscript", "Text", "Draft", "Body"] } });

test("template engine resolves known and unknown variables", () => assert.equal(new TemplateEngine().render("{BookTitle} — {Unknown}", { BookTitle: "North" }), "North —"));
test("internal links retain visible text", () => assert.equal(stripInternalLinks("[[People/Elin|Elin Andersson]] met [[Noah]]."), "Elin Andersson met Noah."));
test("cleaning pipeline removes optional plugin syntax without plugin APIs", () => { const profile = createDefaultProfiles()[0]; profile.removeDataviewBlocks = true; profile.removeCallouts = true; const output = new ContentCleaningPipeline().clean("> [!note] Note\n> Body\n\n```dataview\nTABLE x\n```", profile); assert.equal(output.trim(), "Body"); });
test("callouts convert to plain text while ordinary blockquotes remain quoted", () => {
  const callout = "> [!note]+ Author note\n> First line.\n> Second line.\n>> Nested quoted line.\n\n> Ordinary quotation.";
  assert.equal(removeCallouts(callout), "First line.\nSecond line.\n> Nested quoted line.\n\n> Ordinary quotation.");
  const profile = createDefaultProfiles()[0]; profile.removeCallouts = false;
  assert.match(new ContentCleaningPipeline().clean(callout, profile), /\[!note\]\+ Author note/);
});
test("metadata equality and inequality filters", () => { const engine = new MetadataFilterEngine(); const metadata = { values: { pov: "Elin", editingstatus: "Complete" } }; assert.equal(engine.matches(metadata, [{ id: "1", field: "POV", operator: "equals", value: "Elin" }]).included, true); assert.equal(engine.matches(metadata, [{ id: "2", field: "Editing Status", operator: "not-equals", value: "Complete" }]).included, false); });
test("ordering prioritizes metadata then numeric names", () => { const a = file("Scene 10", "a", { scene: 10 }); const b = file("Scene 2", "b", { scene: 2 }); a.metadata.scene = 10; b.metadata.scene = 2; sortDocuments([a, b], true); assert.equal([a, b].sort(() => 0)[0].title, "Scene 10"); const docs = [a, b]; sortDocuments(docs, true); assert.equal(docs[0].title, "Scene 2"); });
test("number extraction handles padded, word, punctuation, Unicode, and long names", () => { assert.equal(extractNumber("Chapter 01"), 1); assert.equal(extractNumber("Chapter One"), 1); assert.equal(extractNumber("Chapter 10: Ωmega"), 10); assert.equal(extractNumber(`Chapter 42 — ${"Long ".repeat(40)}Title`), 42); assert.equal(titleName("Chapter Twenty-One: Return"), "Return"); assert.equal(titleName("Chapter One"), ""); assert.equal(titleName("Part 1 - The Silence Breaks"), "The Silence Breaks"); assert.equal(titleName("Chapter 01 - Title"), "Title"); assert.equal(titleName("01 Chapter Title"), "Title"); assert.equal(titleName("01 Opening Scene"), "Opening Scene"); });
test("scanner ignores hidden files and retains nested unexpected Markdown", () => { const markdown = Object.assign(new TFile(), { name: "Nested.md", path: "Book/Part 1/Chapter 1/Extra/Nested.md", extension: "md", basename: "Nested" }); const hidden = Object.assign(new TFile(), { name: ".hidden.md", path: "Book/Part 1/.hidden.md", extension: "md", basename: ".hidden" }); const extra = Object.assign(new TFolder(), { name: "Extra", path: "Book/Part 1/Chapter 1/Extra", children: [markdown] }); const chapter = Object.assign(new TFolder(), { name: "Chapter 1", path: "Book/Part 1/Chapter 1", children: [extra] }); const part = Object.assign(new TFolder(), { name: "Part 1", path: "Book/Part 1", children: [chapter, hidden] }); const root = Object.assign(new TFolder(), { name: "Book", path: "Book", children: [part] }); const scan = new VaultScanner().scan(root as never); assert.equal(scan.allMarkdown.length, 1); assert.equal(scan.allMarkdown[0].name, "Nested.md"); });
test("parser reads metadata and excludes matching status", async () => { const source = "---\nScene: 1\nEditing Status: Excluded\n---\nBody"; const fakeFile = { path: "Book/Part 1/Chapter 1/Scene 1.md", name: "Scene 1.md", basename: "Scene 1" } as never; const vault = { cachedRead: async () => source } as never; const scan = { root: { name: "Book", path: "Book" }, frontMatter: [], backMatter: [], looseScenes: [], parts: [{ folder: { name: "Part 1", path: "Book/Part 1" }, looseScenes: [], chapters: [{ folder: { name: "Chapter 1", path: "Book/Part 1/Chapter 1" }, scenes: [fakeFile] }] }], allMarkdown: [fakeFile], warnings: [] } as never; const book = await new ManuscriptParser(vault).parse(scan, createDefaultProfiles()[0]); assert.equal(book.parts[0].chapters[0].scenes[0].excluded, true); });
test("parser reports invalid metadata without aborting", async () => { const fakeFile = { path: "Book/Part 1/Chapter 1/Scene 1.md", name: "Scene 1.md", basename: "Scene 1" } as never; const vault = { cachedRead: async () => "---\ninvalid yaml\n---\nBody" } as never; const scan = { root: { name: "Book", path: "Book" }, frontMatter: [], backMatter: [], looseScenes: [], parts: [{ folder: { name: "Part 1", path: "Book/Part 1" }, looseScenes: [], chapters: [{ folder: { name: "Chapter 1", path: "Book/Part 1/Chapter 1" }, scenes: [fakeFile] }] }], allMarkdown: [fakeFile], warnings: [] } as never; const book = await new ManuscriptParser(vault).parse(scan, createDefaultProfiles()[0]); assert.ok(book.warnings.some((warning) => warning.includes("Invalid metadata"))); });
test("parser supports chapter notes in manuscripts without Parts", async () => { const chapterFile = { path: "Book/Chapter 1.md", name: "Chapter 1.md", basename: "Chapter 1" } as never; const vault = { cachedRead: async () => "---\nChapter: 1\n---\nChapter prose" } as never; const scan = { root: { name: "Book", path: "Book" }, frontMatter: [], backMatter: [], looseScenes: [chapterFile], parts: [], allMarkdown: [chapterFile], warnings: [] } as never; const profile = createDefaultProfiles()[0]; profile.useParts = false; profile.chapterSource = "notes"; const book = await new ManuscriptParser(vault).parse(scan, profile); assert.equal(book.parts[0].chapters[0].title, "Chapter 1"); const stats = new StatisticsEngine().calculate(book, profile, 250); assert.match(new MarkdownGenerator().generate(book, profile, stats), /^## Chapter 1/); });
test("bounded concurrency processes every item", async () => { const seen: number[] = []; await mapConcurrent([1, 2, 3, 4], 2, async (value) => { seen.push(value); }); assert.deepEqual(seen.sort(), [1, 2, 3, 4]); });
test("bounded parsing cancels without processing the remaining queue", async () => { const controller = new AbortController(); const seen: number[] = []; await assert.rejects(mapConcurrent([1, 2, 3, 4], 1, async (value) => { seen.push(value); controller.abort(); }, controller.signal), CompilationCancelledError); assert.deepEqual(seen, [1]); });
test("statistics and Markdown generation are deterministic", () => { const scene = file("Scene 1", "one two three"); const profile = createDefaultProfiles()[0]; const book = { root: { path: "Book", name: "Book" }, title: "Book", frontMatter: { kind: "front", title: "Front Matter", documents: [] }, parts: [{ title: "Part 1", name: "Part 1", number: 1, path: "Book/Part 1", chapters: [{ title: "Chapter 1", name: "Chapter 1", number: 1, path: "Book/Part 1/Chapter 1", scenes: [scene], orphan: false }], orphanScenes: [] }], orphanScenes: [], backMatter: { kind: "back", title: "Back Matter", documents: [] }, includedFiles: [scene.file], excludedFiles: [], warnings: [], issues: [] } as Book; const stats = new StatisticsEngine().calculate(book, profile, 250); assert.equal(stats.totalWordCount, 3); const generator = new MarkdownGenerator(); const date = new Date("2026-01-02T00:00:00Z"); assert.equal(generator.generate(book, profile, stats, date), generator.generate(book, profile, stats, date)); assert.match(generator.generate(book, profile, stats, date), /^# Part 1/); const issues = new WarningEngine().analyze(book, profile, "Exports/Book.md"); assert.ok(issues.some((issue) => issue.code === "missing-front-matter")); });
test("output paths reject traversal, absolute paths, and nonportable characters", () => { assert.equal(validateVaultPath("Exports/Book"), "Exports/Book"); assert.throws(() => validateVaultPath("../Book"), /traversal/); assert.throws(() => validateVaultPath("/tmp/Book"), /vault-relative/); assert.throws(() => validateVaultPath("C:\\Book"), /vault-relative/); assert.throws(() => validateVaultPath("Exports/Bad?Name"), /portable/); });
test("blocking output safety errors disable export", () => { assert.equal(canProceedWithExport([{ severity: "error", code: "output-inside-root", message: "unsafe" }], "markdown", true), false); assert.equal(canProceedWithExport([{ severity: "warning", code: "output-exists", message: "confirm" }], "markdown", true), true); assert.equal(canProceedWithExport([], "docx", false), false); });
test("native DOCX defaults require no desktop or Pandoc state", () => { assert.equal(DEFAULT_SETTINGS.defaultExportFormat, "docx"); assert.equal(DEFAULT_SETTINGS.defaultDocxStyle, "vellum"); assert.equal(DEFAULT_SETTINGS.automaticallyDetectPandoc, false); });
for (const preset of ["novel-parts", "novel", "chapter-notes", "short-story", "anthology", "custom"] as const) test(`simple workflow resolves ${preset}`, () => { const base = createDefaultProfiles()[0]; const profile = resolveSimpleCompileRequest({ manuscriptRoot: "Books/Test", structurePreset: preset, includeFrontMatter: true, includeBackMatter: false, exportFolder: "Exports", outputFilename: "Test.docx", outputFormat: "docx", docxPreset: "vellum", custom: { useParts: false, chapterSource: "folders" } }, base); assert.equal(profile.manuscriptRoot, "Books/Test"); assert.equal(profile.exportFolder, "Exports"); assert.equal(profile.exportTarget, "docx"); assert.equal(profile.referenceDocx, ""); });
test("Vellum preset applies safe cleaning and readable links", () => { const profile = resolveSimpleCompileRequest({ manuscriptRoot: "Book", structurePreset: "novel-parts", includeFrontMatter: true, includeBackMatter: true, exportFolder: "Exports", outputFilename: "Book.docx", outputFormat: "docx", docxPreset: "vellum" }, createDefaultProfiles()[0]); assert.equal(profile.removeDataviewBlocks, true); assert.equal(profile.removeCallouts, true); assert.equal(profile.stripInternalLinks, true); assert.equal(profile.generateTableOfContents, false); });
test("TOC selection survives preset resolution as a real compile-request choice", () => { const profile = resolveSimpleCompileRequest({ manuscriptRoot: "Book", structurePreset: "novel-parts", includeFrontMatter: true, includeBackMatter: true, exportFolder: "Exports", outputFilename: "Book.docx", outputFormat: "docx", docxPreset: "vellum", tableOfContents: true }, createDefaultProfiles()[0]); assert.equal(profile.generateTableOfContents, true); });
test("Standard DOCX preset uses conventional filename ordering", () => { const profile = resolveSimpleCompileRequest({ manuscriptRoot: "Book", structurePreset: "novel", includeFrontMatter: true, includeBackMatter: true, exportFolder: "Exports", outputFilename: "Book.docx", outputFormat: "docx", docxPreset: "standard" }, createDefaultProfiles()[0]); assert.equal(profile.orderingMethod, "filename"); assert.equal(profile.stripYamlFrontmatter, true); });
test("Vellum, Standard, and Custom DOCX formatting resolve deterministically", () => {
  assert.deepEqual(docxFormattingForPreset("vellum"), DOCX_FORMATTING_PRESETS.vellum);
  assert.deepEqual(docxFormattingForPreset("standard"), DOCX_FORMATTING_PRESETS.standard);
  assert.deepEqual(docxFormattingForPreset("vellum"), docxFormattingForPreset("vellum"));
  const custom = { font: "Georgia", fontSize: 13, lineSpacing: 1.5, firstLineIndent: 0.25, pageSize: "a4" as const, chapterPageBreak: false, titlePage: true };
  assert.deepEqual(docxFormattingForPreset("custom", true, custom), custom);
  assert.equal(DOCX_FORMATTING_PRESETS.vellum.chapterPageBreak, true);
  assert.equal(DOCX_FORMATTING_PRESETS.standard.chapterPageBreak, true);
  assert.equal(DOCX_FORMATTING_PRESETS.standard.fontSize, 12);
  assert.equal(DOCX_FORMATTING_PRESETS.standard.lineSpacing, 2);
});
test("simple workflow validates missing folders and invalid filenames", () => { const request = { manuscriptRoot: "", structurePreset: "novel" as const, includeFrontMatter: true, includeBackMatter: true, exportFolder: "Exports", outputFilename: "bad/name.docx", outputFormat: "docx" as const, docxPreset: "standard" as const }; const errors = validateSimpleCompileRequest(request); assert.ok(errors.some((item) => /folder/i.test(item))); assert.ok(errors.some((item) => /filename/i.test(item))); });
test("custom workflow preserves advanced profile options", () => { const base = createDefaultProfiles()[0]; base.metadataFilters = [{ id: "1", field: "POV", operator: "equals", value: "Elin" }]; const profile = resolveSimpleCompileRequest({ manuscriptRoot: "Book", structurePreset: "custom", includeFrontMatter: true, includeBackMatter: true, exportFolder: "Exports", outputFilename: "Book.docx", outputFormat: "docx", docxPreset: "standard", custom: { sceneSeparator: "***" } }, base); assert.equal(profile.sceneSeparator, "***"); assert.equal(profile.metadataFilters.length, 1); });
test("structure inference preserves existing layout", () => { const profile = createDefaultProfiles()[0]; profile.useParts = false; profile.chapterSource = "notes"; assert.equal(inferStructurePreset(profile), "chapter-notes"); });
test("Markdown export uses documented vault APIs on non-filesystem adapters", async () => { const entries = new Map<string, unknown>(); const vault = { adapter: {}, getAbstractFileByPath: (value: string) => entries.get(value) ?? null, createFolder: async (value: string) => { entries.set(value, { path: value }); }, create: async (value: string, content: string) => { const created = Object.assign(new TFile(), { path: value, extension: "md", content }); entries.set(value, created); return created; }, modify: async (item: { content: string }, content: string) => { item.content = content; } } as never; const file = await new MarkdownExporter(vault).write("Exports/Test.md", "Body\n"); assert.equal((file as unknown as { content: string }).content, "Body\n"); });
test("content cleaners cover YAML, comments, Dataview, callouts, links, embeds, blocks, and line endings", () => { assert.equal(stripYamlFrontmatter("---\r\ntitle: Test\r\n---\r\nBody"), "Body"); assert.equal(removeHtmlComments("A<!-- x -->B"), "AB"); assert.equal(removeObsidianComments("A%% x %%B"), "AB"); assert.equal(removeDataviewBlocks("A\n```dataviewjs\nx\n```\nB"), "A\nB"); assert.equal(removeCallouts("> [!note] Title\n> Body\n\n> Ordinary"), "Body\n\n> Ordinary"); assert.equal(stripInternalLinks("[[Note]] [[Folder/Note|Alias]] [[Note#^block]] ![[image.png]] ![[Embedded Note]]"), "Note Alias Note image.png Embedded Note"); });
test("manuscript metadata cleaning removes exact leaked property formats only at structured boundaries", () => { const source = "**Series:** The Watchers of Silence Series Dashboard\nBook:: [[Warden of Silence Dashboard]]\nPart: Part 1 - The Silence Breaks\nChapter: Chapter 1 - The Silence of Östersund\nScene Number: 2\nCharacters:\n  - Henrik\n\nActual prose begins with Book in an ordinary sentence.\n\nEditing Status: Included"; const cleaned = removeProjectMetadataRegions(source); assert.equal(cleaned, "Actual prose begins with Book in an ordinary sentence."); assert.doesNotMatch(cleaned, /Dashboard|Part 1|Chapter 1|Henrik|Editing Status/); });
test("scene body extraction omits synopsis and revision sections", () => { const source = "---\nBook: Warden of Silence Dashboard\n---\n# Synopsis\nInternal synopsis.\n# Scene\nActual manuscript prose.\n# Revision Notes\nInternal revision notes."; assert.equal(cleanManuscriptContent(source), "Actual manuscript prose."); });
test("validation engine reports the prepared semantic manuscript without export", async () => { const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const profile = createDefaultProfiles()[0]; profile.partHeadingTemplate = ""; const service = new CompilePreparationService(loaded.vault as never, profile, 250); const session = await service.prepareAuthoritative({ manuscriptRoot: loaded.root.path, profile, structurePreset: "novel-parts", purpose: "validation", route: "validation" }); const settings = { configurationWarnings: [] } as never; const result = await new ManuscriptValidationService(loaded.vault as never, settings).validate(session); assert.ok(result.issues.some((issue) => issue.code === "invalid-profile" || issue.code === "invalid-template")); assert.equal(result.book, session.book); assert.equal(result.statistics.sceneCount, 3); });
test("validation detects outputs inside manuscript roots including vault root", () => { const profile = createDefaultProfiles()[0]; const emptyBook = { root: { path: "/", name: "Vault" }, title: "Vault", frontMatter: { kind: "front", title: "Front", documents: [] }, backMatter: { kind: "back", title: "Back", documents: [] }, parts: [], orphanScenes: [], includedFiles: [], excludedFiles: [], warnings: [], issues: [] } as unknown as Book; assert.ok(new WarningEngine().analyze(emptyBook, profile, "Exports/Book.md").some((issue) => issue.code === "output-inside-root")); });
test("Stage 5 profiles migrate to release-candidate structure", () => { const old = createDefaultProfiles()[0] as unknown as Record<string, unknown>; delete old.chapterSource; delete old.useParts; const settings = { ...DEFAULT_SETTINGS, profiles: [old], activeProfileId: old.id, defaultProfileId: old.id } as never; const repaired = repairSettings(settings); assert.equal(repaired.profiles[0].chapterSource, "folders"); assert.equal(repaired.profiles[0].useParts, true); });
test("profile wizard creates a usable Vellum note-chapter profile", () => { const profile = profileFromWizard({ name: "Submission", manuscriptRoot: "Books/Submission", exportFolder: "Exports", chapterSource: "notes", useParts: false, sceneSeparators: false, includeFrontMatter: true, includeBackMatter: false, referenceDocx: "", vellum: true }); assert.equal(profile.chapterSource, "notes"); assert.equal(profile.useParts, false); assert.equal(profile.sceneSeparator, ""); assert.match(profile.chapterHeadingTemplate, /Chapter/); });
test("diagnostics excludes manuscript content and reports timings", () => { const profile = createDefaultProfiles()[0]; const settings = { ...DEFAULT_SETTINGS, profiles: [profile], activeProfileId: profile.id, defaultProfileId: profile.id, compileLogs: [{ id: "1", timestamp: "2026-01-01", profile: profile.name, manuscript: "Book", outputFiles: [], wordCount: 10, success: true, exportFormats: "markdown", compilerVersion: "0.6.0", durationMs: 10, scanDurationMs: 1, parseDurationMs: 2, filterDurationMs: 1, generationDurationMs: 3, exportDurationMs: 1, warnings: [] }] } as never; const report = new DiagnosticsReportGenerator().generate({ pluginVersion: "0.8.0", obsidianVersion: "1.13.1", operatingSystem: "Test OS", profile, settings, generatedAt: new Date("2026-01-01T00:00:00Z") }); assert.match(report, /Parse: 2 ms/); assert.match(report, /Built in/); assert.match(report, /intentionally excludes manuscript contents/); });
test("diagnostics redact absolute paths, legacy reference paths, and filter values", () => { const profile = createDefaultProfiles()[0]; profile.manuscriptRoot = "/Users/alice/SecretBook"; profile.referenceDocx = "/Users/alice/Templates/private.docx"; profile.metadataFilters = [{ id: "1", field: "POV", operator: "equals", value: "SecretName" }]; const settings = { ...DEFAULT_SETTINGS, profiles: [profile], activeProfileId: profile.id, defaultProfileId: profile.id } as never; const report = new DiagnosticsReportGenerator().generate({ pluginVersion: "0.8.0", obsidianVersion: "1.13.1", operatingSystem: "Mac /Users/alice", profile, settings }); assert.doesNotMatch(report, /alice|private\.docx|SecretName/); });

for (const version of ["0.1", "0.2", "0.3", "0.4", "0.5", "0.6"]) test(`settings migration is repeatable from ${version}`, () => { const legacyProfile = createDefaultProfiles()[0] as unknown as Record<string, unknown>; legacyProfile.manuscriptRoot = "Books/Legacy"; legacyProfile.exportFolder = "Exports/Legacy"; if (version < "0.4") { delete legacyProfile.exportTarget; delete legacyProfile.referenceDocx; } if (version < "0.6") { delete legacyProfile.useParts; delete legacyProfile.chapterSource; } const hasProfiles = version >= "0.3"; const originalId = legacyProfile.id as string; const legacy = { ...DEFAULT_SETTINGS, profiles: hasProfiles ? [legacyProfile] : [], activeProfileId: hasProfiles ? originalId : "", defaultProfileId: hasProfiles ? originalId : "", defaultManuscriptFolder: "Books/Legacy", defaultExportFolder: "Exports/Legacy", includeBackMatter: false } as never; const once = repairSettings(legacy); const snapshot = JSON.stringify(once); const twice = repairSettings(once); assert.equal(JSON.stringify(twice), snapshot); assert.ok(twice.profiles.length >= 1); const migrated = twice.profiles.find((profile) => profile.manuscriptRoot === "Books/Legacy"); assert.ok(migrated); if (hasProfiles) assert.equal(migrated.id, originalId); else assert.equal(migrated.includeBackMatter, false); });
test("large-manuscript pipeline handles 500 chapters, 2,000 scenes, and 2 million words", async () => { const profile = createDefaultProfiles()[0]; const content = `${"word ".repeat(999)}word`; let sceneIndex = 0; const allMarkdown: Array<{ name: string; basename: string; path: string }> = []; const parts = Array.from({ length: 10 }, (_, partIndex) => ({ folder: { name: `Part ${partIndex + 1}`, path: `Book/Part ${partIndex + 1}` }, looseScenes: [], chapters: Array.from({ length: 50 }, (_, chapterIndex) => ({ folder: { name: `Chapter ${partIndex * 50 + chapterIndex + 1}`, path: `Book/Part ${partIndex + 1}/Chapter ${chapterIndex + 1}` }, scenes: Array.from({ length: 4 }, () => { const name = `Scene ${++sceneIndex}`; const scene = { name: `${name}.md`, basename: name, path: `Book/Part ${partIndex + 1}/Chapter ${chapterIndex + 1}/${name}.md` }; allMarkdown.push(scene); return scene; }) })) })); const scan = { root: { path: "Book", name: "Book" }, frontMatter: [], backMatter: [], looseScenes: [], parts, allMarkdown, warnings: [] } as never; const started = performance.now(); const book = await new ManuscriptParser({ cachedRead: async () => content } as never).parse(scan, profile); const stats = new StatisticsEngine().calculate(book, profile, 250); const generator = new MarkdownGenerator(); const date = new Date("2026-01-01T00:00:00Z"); const markdown = generator.generate(book, profile, stats, date); assert.equal(stats.chapterCount, 500); assert.equal(stats.sceneCount, 2000); assert.equal(stats.totalWordCount, 2_000_000); assert.equal(generator.generate(book, profile, stats, date), markdown); assert.ok(markdown.length > 9_000_000); const duration = performance.now() - started; assert.ok(duration < 15_000, `Possible runaway regression: expected under 15 seconds, received ${Math.round(duration)} ms`); process.stdout.write(`  synthetic full parse-to-Markdown correctness run: ${Math.round(duration)} ms (informational)\n`); });

for (const fixture of [
  { name: "complete-sample", folder: "Complete Sample Book", useParts: true, chapterSource: "folders" as const, vellum: true },
  { name: "novel-with-parts", folder: "Novel with Parts", useParts: true, chapterSource: "folders" as const, vellum: false },
  { name: "small-novel", folder: "Small Novel", useParts: false, chapterSource: "folders" as const, vellum: false },
  { name: "short-story", folder: "Short Story", useParts: false, chapterSource: "notes" as const, vellum: false },
  { name: "anthology", folder: "Anthology", useParts: true, chapterSource: "notes" as const, vellum: false },
  { name: "mixed-malformed", folder: "Mixed and Malformed", useParts: true, chapterSource: "notes" as const, vellum: false }
]) test(`golden Markdown: ${fixture.name}`, async () => { const loaded = await loadFixtureScan(path.join("samples", fixture.folder)); const profile = createDefaultProfiles()[fixture.vellum ? 1 : 0]; profile.useParts = fixture.useParts; profile.chapterSource = fixture.chapterSource; profile.removeDataviewBlocks = true; profile.removeHtmlComments = true; profile.removeCallouts = true; profile.stripInternalLinks = true; const parser = new ManuscriptParser(loaded.vault as never); const book = await parser.parse(loaded.scan, profile); const stats = new StatisticsEngine().calculate(book, profile, 250); const markdown = new MarkdownGenerator().generate(book, profile, stats, new Date("2026-01-01T00:00:00Z")); const goldenPath = path.join("tests", "golden", `${fixture.name}.md`); if (process.env.UPDATE_GOLDEN === "1") { await mkdir(path.dirname(goldenPath), { recursive: true }); await writeFile(goldenPath, markdown, "utf8"); } const expected = await readFile(goldenPath, "utf8"); assert.equal(markdown, expected); assert.doesNotMatch(markdown, /^---$/m); assert.doesNotMatch(markdown, /\[\[/); if (fixture.name === "complete-sample") assert.ok(book.warnings.some((warning) => warning.includes("Duplicate scene"))); if (fixture.name === "mixed-malformed") { assert.ok(book.warnings.some((warning) => warning.includes("Invalid metadata"))); assert.ok(book.warnings.some((warning) => warning.includes("Orphan scene"))); } });

test("0.7 settings migrate idempotently into the simplified model", () => { const profile = createDefaultProfiles()[0]; profile.manuscriptRoot = "Books/Existing"; profile.exportFolder = "Exports/Existing"; profile.outputFilename = "Existing.docx"; const legacy = { ...DEFAULT_SETTINGS, profiles: [profile], activeProfileId: profile.id, defaultProfileId: profile.id } as Record<string, unknown>; delete legacy.defaultStructurePreset; delete legacy.defaultDocxStyle; delete legacy.warnBeforeOverwrite; delete legacy.openAfterCompile; delete legacy.showAdvancedOptions; const once = repairSettings(legacy as never); const snapshot = JSON.stringify(once); const twice = repairSettings(once); assert.equal(JSON.stringify(twice), snapshot); assert.equal(once.profiles[0].manuscriptRoot, "Books/Existing"); assert.equal(once.profiles[0].exportFolder, "Exports/Existing"); assert.equal(once.profiles[0].outputFilename, "Existing.docx"); assert.equal(once.defaultStructurePreset, "novel-parts"); });
test("saved Chapter page-break compatibility values survive repair", () => { const profile = { ...createDefaultProfiles()[0], docxChapterPageBreak: false }; const settings = repairSettings({ ...DEFAULT_SETTINGS, profiles: [profile], activeProfileId: profile.id, defaultProfileId: profile.id } as never); assert.equal(settings.profiles[0].docxChapterPageBreak, false); });
test("0.9.1 settings migrate to 0.9.2 idempotently without losing author choices", () => {
  const profile = { ...createDefaultProfiles()[0], name: "My 0.9.1 Profile", manuscriptRoot: "Books/My Novel", exportFolder: "Exports/Books", outputFilename: "{BookTitle}.docx", variables: { BookTitle: "My Novel", Series: "My Series", Author: "A. Writer" }, metadataFilters: [{ id: "filter-1", field: "Status", operator: "not-equals" as const, value: "Excluded" }], stripInternalLinks: true, removeCallouts: false, bodySectionAliases: ["Scene", "Body"], docxFont: "Georgia", docxFontSize: 13, docxLineSpacing: 1.5, docxFirstLineIndent: 0.25, docxPageSize: "a4" as const, docxChapterPageBreak: false, docxTitlePage: true, generateTableOfContents: true };
  const history = [{ id: "history-1", timestamp: "2026-07-01T10:00:00.000Z", profile: profile.name, manuscript: profile.manuscriptRoot, outputFiles: ["Exports/Books/My Novel.docx"], wordCount: 1234, success: true }];
  const persisted = { ...DEFAULT_SETTINGS, profiles: [profile], activeProfileId: profile.id, defaultProfileId: profile.id, defaultManuscriptFolder: profile.manuscriptRoot, defaultExportFolder: profile.exportFolder, defaultStructurePreset: "novel-parts" as const, defaultDocxStyle: "standard" as const, includeTitlePageByDefault: true, includeTableOfContentsByDefault: true, exportHistory: history, compileLogs: [], showAdvancedOptions: true };
  const once = repairSettings(structuredClone(persisted)); const snapshot = JSON.stringify(once); const twice = repairSettings(once);
  assert.equal(JSON.stringify(twice), snapshot); const migrated = twice.profiles[0];
  assert.deepEqual({ root: migrated.manuscriptRoot, folder: migrated.exportFolder, filename: migrated.outputFilename, variables: migrated.variables, filters: migrated.metadataFilters, font: migrated.docxFont, size: migrated.docxFontSize, spacing: migrated.docxLineSpacing, indent: migrated.docxFirstLineIndent, page: migrated.docxPageSize, chapterBreak: migrated.docxChapterPageBreak, titlePage: migrated.docxTitlePage, toc: migrated.generateTableOfContents }, { root: profile.manuscriptRoot, folder: profile.exportFolder, filename: profile.outputFilename, variables: profile.variables, filters: profile.metadataFilters, font: "Georgia", size: 13, spacing: 1.5, indent: 0.25, page: "a4", chapterBreak: false, titlePage: true, toc: true });
  assert.equal(twice.activeProfileId, profile.id); assert.equal(twice.defaultProfileId, profile.id); assert.equal(twice.exportHistory[0].id, "history-1"); assert.equal(twice.showAdvancedOptions, true);
});
test("first-run defaults are DOCX, Vellum, previewed, and overwrite-safe", () => { assert.equal(DEFAULT_SETTINGS.defaultExportFormat, "docx"); assert.equal(DEFAULT_SETTINGS.defaultDocxStyle, "vellum"); assert.equal(DEFAULT_SETTINGS.showPreview, true); assert.equal(DEFAULT_SETTINGS.warnBeforeOverwrite, true); assert.equal(DEFAULT_SETTINGS.showAdvancedOptions, false); });
test("simple workflow output path uses the requested folder and filename", () => { const exporter = new MarkdownExporter({} as never); assert.equal(exporter.getOutputPath("Manuscript Exports", "Warden of Silence.docx", {}, ".docx"), "Manuscript Exports/Warden of Silence.docx"); });
test("existing-output warnings do not block overwrite handling", () => { assert.equal(canProceedWithExport([{ severity: "warning", code: "output-exists", message: "Already exists" }], "docx", true), true); });
test("native DOCX generation has no platform or executable prerequisite", () => { const bytes = createTestDocx("Text", "Book"); assert.equal(String.fromCharCode(bytes[0], bytes[1]), "PK"); });
test("Warden regression exports only publishable content through a transparent Manuscript container", async () => { const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const role = (suffix: string) => plan.find((item) => item.path.endsWith(suffix)); assert.equal(role("/Manuscript")?.role, "transparent"); for (const folder of ["Archive", "Development", "Exports"]) { assert.equal(role(`/${folder}`)?.role, "ignore"); assert.equal(role(`/${folder}`)?.included, false); } assert.equal(role("/Warden of Silence Dashboard.md")?.role, "ignore"); const profile = createDefaultProfiles()[1]; profile.useParts = true; profile.chapterSource = "folders"; profile.contentOrder = plan.filter((item) => item.included).map((item) => item.path); profile.bodySectionAliases = ["Scene", "Manuscript", "Text", "Draft", "Body"]; const scan = applyContentPlan(new VaultScanner().scan(loaded.root), plan, profile); const book = await new ManuscriptParser(loaded.vault as never).parse(scan, profile); const markdown = new MarkdownGenerator().generate(book, profile, new StatisticsEngine().calculate(book, profile, 250), new Date("2026-01-01")); const forbidden = ["Archive", "Development", "Previous Export", "Dashboard", "Revision Notes", "Internal synopsis", "Editing Status", "Characters:", "Part 0", "Chapter 0", "# Manuscript"]; forbidden.forEach((value) => assert.doesNotMatch(markdown, new RegExp(value, "i"), value)); assert.equal((markdown.match(/The Silence Breaks/g) ?? []).length, 1); assert.equal((markdown.match(/The Silence of Östersund/g) ?? []).length, 1); assert.equal((markdown.match(/Östersund was silent/g) ?? []).length, 1); assert.equal((markdown.match(/The barn door opened/g) ?? []).length, 1); assert.ok(markdown.indexOf("Copyright ©") < markdown.indexOf("The Silence Breaks")); assert.ok(markdown.indexOf("The Weight of Knowing") < markdown.indexOf("With gratitude")); assert.equal((markdown.match(/^#$/gm) ?? []).length, 1); });

test("prepared preview is built from the final Warden Book model used by DOCX", async () => { const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const request = preparedRequest(loaded.root.path, plan); const session = await new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250).prepare(request, plan); assert.equal(session.book.title, "Book 1 - Warden of Silence"); assert.equal(session.book.parts.length, 2); assert.deepEqual(session.book.parts.map((part) => part.chapters.map((chapter) => [chapter.name, chapter.scenes.filter((scene) => !scene.excluded && scene.content.trim()).length])), [[ ["The Silence of Östersund", 2] ], [ ["The Cold Welcome", 1] ]]); assert.equal(session.statistics.sceneCount, 3); assert.equal(session.book.frontMatter.documents.filter((item) => !item.excluded && item.content.trim()).length, 2); assert.equal(session.book.backMatter.documents.filter((item) => !item.excluded && item.content.trim()).length, 1); assert.ok(sessionMatchesBook(session, session.book)); assert.equal(createPreparedExportRequest(session, session.outputPaths[0], false).book, session.book); const bytes = createManuscriptDocx(session.book, session.profile, { title: "Warden of Silence", author: "Anthony Fitzpatrick", titlePage: true, partDisplay: "word-title", chapterDisplay: "word-title" }); const document = strFromU8(unzipSync(bytes)["word/document.xml"]); const forbidden = ["Archive", "Development", "Exports", "Dashboard", "Revision Notes", "Synopsis", "Internal synopsis", "Editing Status", "Characters:", "The Watchers of Silence Series Dashboard"]; for (const value of forbidden) { assert.doesNotMatch(session.result.markdown, new RegExp(value, "i")); assert.doesNotMatch(document, new RegExp(value, "i")); } });

test("empty cleaned notes are excluded from both prepared preview counts and DOCX", async () => { const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const emptyPath = `${loaded.root.path}/Manuscript/Part 1 - The Silence Breaks/Chapter 1 - The Silence of Östersund/Scene 2 - The Barn.md`; loaded.setContent(emptyPath, "# Synopsis\n\nOnly an internal synopsis.\n\n# Revision Notes\n\nNothing publishable."); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const emptyItem = plan.find((item) => item.path === emptyPath)!; emptyItem.included = true; emptyItem.role = "scene"; emptyItem.userOverride = true; const request = preparedRequest(loaded.root.path, plan); const session = await new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250).prepare(request, plan); assert.equal(session.statistics.sceneCount, 2); assert.ok(session.exclusions.some((item) => item.path === emptyPath && /No manuscript body remains/i.test(item.reason))); const document = strFromU8(unzipSync(createManuscriptDocx(session.book, session.profile, { title: "Warden", author: "Author" }))["word/document.xml"]); assert.doesNotMatch(session.result.markdown, /Only an internal synopsis|Nothing publishable/); assert.doesNotMatch(document, /Only an internal synopsis|Nothing publishable/); });

test("prepared-session input signatures invalidate on inclusion, role, order, and root changes", async () => { const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const request = preparedRequest(loaded.root.path, plan); const session = await new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250).prepare(request, plan); assert.ok(preparedSessionMatchesInputs(session, request, plan)); const target = plan.find((item) => item.kind === "note" && item.included)!; const included = target.included; target.included = !included; assert.ok(!preparedSessionMatchesInputs(session, request, plan)); target.included = included; const role = target.role; target.role = role === "scene" ? "chapter" : "scene"; assert.ok(!preparedSessionMatchesInputs(session, request, plan)); target.role = role; const order = target.order; target.order += 1; assert.ok(!preparedSessionMatchesInputs(session, request, plan)); target.order = order; const root = request.manuscriptRoot; request.manuscriptRoot = `${root} changed`; assert.ok(!preparedSessionMatchesInputs(session, request, plan)); request.manuscriptRoot = root; assert.equal(compileInputSignature(request, plan), session.inputSignature); });

test("source changes block a prepared session and refresh preparation rebuilds it", async () => { const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const request = preparedRequest(loaded.root.path, plan); const service = new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250); const first = await service.prepare(request, plan); const scenePath = `${loaded.root.path}/Manuscript/Part 2 - The Weight of Knowing/Chapter 11 - The Cold Welcome/Scene 1.md`; loaded.setContent(scenePath, "# Scene\n\nFresh preview prose after a source edit."); assert.notEqual(await calculateSourceFingerprint(loaded.vault as never, first.sourcePaths), first.sourceFingerprint); const refreshed = await service.prepare(request, plan); assert.notEqual(refreshed.sourceFingerprint, first.sourceFingerprint); assert.match(refreshed.result.markdown, /Fresh preview prose after a source edit/); assert.doesNotMatch(first.result.markdown, /Fresh preview prose after a source edit/); });

test("all automatic compile routes produce the same safe Warden semantic manuscript", async () => {
  const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const profile = createDefaultProfiles()[1];
  profile.explicitlyIncludedPaths = [`${loaded.root.path}/Archive/Old Chapter.md`];
  const service = new CompilePreparationService(loaded.vault as never, profile, 250);
  const routes = ["current-book", "selected-folder", "legacy-profile", "validation", "sample"] as const;
  const sessions = await Promise.all(routes.map((route) => service.prepareAuthoritative({ manuscriptRoot: loaded.root.path, profile, structurePreset: "novel-parts", purpose: route === "validation" ? "validation" : "compile", route })));
  const semantic = (session: typeof sessions[number]) => ({ front: session.book.frontMatter.documents.filter((item) => !item.excluded && item.content.trim()).map((item) => item.title), parts: session.book.parts.map((part) => ({ number: part.number, name: part.name, chapters: part.chapters.map((chapter) => ({ number: chapter.number, name: chapter.name, scenes: chapter.scenes.filter((scene) => !scene.excluded && scene.content.trim()).length })) })), back: session.book.backMatter.documents.filter((item) => !item.excluded && item.content.trim()).map((item) => item.title) });
  const expected = { front: ["Title Page", "Copyright"], parts: [{ number: 1, name: "The Silence Breaks", chapters: [{ number: 1, name: "The Silence of Östersund", scenes: 2 }] }, { number: 2, name: "The Weight of Knowing", chapters: [{ number: 11, name: "The Cold Welcome", scenes: 1 }] }], back: ["Acknowledgements"] };
  const forbidden = ["Archive", "Development", "Exports", "Warden of Silence Dashboard", "The Watchers of Silence Series Dashboard", "Revision Notes", "Synopsis", "Editing Status", "Part 0", "Chapter 0", "# Manuscript", "Chapter 0: Book 1 - Warden of Silence"];
  sessions.forEach((session) => { assert.deepEqual(semantic(session), expected, session.route); forbidden.forEach((value) => assert.doesNotMatch(session.result.markdown, new RegExp(value, "i"), `${session.route}: ${value}`)); assert.ok(session.contentPlan.some((item) => item.name === "Manuscript" && item.role === "transparent")); assert.ok(session.exclusions.some((item) => /Archive\/Old Chapter\.md$/.test(item.path))); });
  sessions.slice(1).forEach((session) => assert.deepEqual(semantic(session), semantic(sessions[0])));
  const validation = await new ManuscriptValidationService(loaded.vault as never, { configurationWarnings: [] } as never).validate(sessions[3]); assert.equal(validation.book, sessions[3].book); assert.equal(validation.statistics.sceneCount, 3);
  const document = strFromU8(unzipSync(createManuscriptDocx(sessions[0].book, sessions[0].profile, { title: "Warden of Silence", author: "Anthony Fitzpatrick" }))["word/document.xml"]); forbidden.forEach((value) => assert.doesNotMatch(document, new RegExp(value, "i"), value));
});

test("guided preparation keeps explicit inclusion, role, and manual order authoritative", async () => {
  const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts"));
  const excluded = plan.find((item) => item.name === "Scene 2 - The Barn")!; excluded.included = false; excluded.userOverride = true;
  const partOne = plan.find((item) => item.name === "Part 1 - The Silence Breaks")!; const partTwo = plan.find((item) => item.name === "Part 2 - The Weight of Knowing")!; partOne.order = 1; partTwo.order = 0; partOne.userOverride = true; partTwo.userOverride = true;
  const request = preparedRequest(loaded.root.path, plan); const session = await new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250).prepare(request, plan);
  assert.deepEqual(session.book.parts.map((part) => part.number), [2, 1]); assert.equal(session.statistics.sceneCount, 2); assert.equal(session.contentPlan.find((item) => item.path === excluded.path)?.userOverride, true); assert.doesNotMatch(session.result.markdown, /The barn door opened/);
});

test("book-root resolution and command identifiers are central and stable", async () => {
  const root = Object.assign(new TFolder(), { name: "Book", path: "Books/Book", children: [] }); const vault = { getAbstractFileByPath: (value: string) => value === root.path ? root : null } as never;
  assert.equal(new BookRootResolver(vault).require(root.path), root); assert.deepEqual(Object.values(COMMAND_IDS), ["compile-manuscript", "compile-current-book", "compile-selected-folder", "validate-manuscript", "generate-diagnostics-report"]); const main = await readFile(path.join("src", "main.ts"), "utf8"); for (const title of ["Compile Manuscript", "Compile Current Book", "Compile Selected Folder", "Validate Manuscript", "Generate Diagnostics Report"]) assert.match(main, new RegExp(`name: "${title}"`));
});

test("production preparation has one scanner-to-semantic boundary", async () => {
  const mainSource = await readFile(path.join("src", "main.ts"), "utf8"); const validationSource = await readFile(path.join("src", "validation.ts"), "utf8"); const preparationSource = await readFile(path.join("src", "compile-preparation.ts"), "utf8"); const exporterSource = await readFile(path.join("src", "exporter.ts"), "utf8");
  assert.doesNotMatch(mainSource, /VaultScanner|buildModel\(|applyContentPlan\(/); assert.doesNotMatch(validationSource, /VaultScanner|buildModel\(|ScannedBook/); assert.match(preparationSource, /new VaultScanner\(\)\.scan/); assert.match(preparationSource, /compiler\.buildModel/); assert.doesNotMatch(exporterSource, /ScannedBook/);
});

test("workspace controller centralises every prepared-session invalidation rule", async () => {
  const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const request = preparedRequest(loaded.root.path, plan); const formatting = request.formatting!;
  const prepared = await new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250).prepare(request, plan);
  const controller = new CompileWorkspaceController(request, formatting, { prepare: async () => prepared, sessionIsCurrent: async () => true, export: async () => undefined }); controller.setDetectedPlan(loaded.root.path, plan);
  const invalidates = (mutation: () => void): void => { controller.state.preparedSession = prepared; mutation(); assert.equal(controller.state.preparedSession, undefined); };
  invalidates(() => controller.setRoot(`${loaded.root.path} changed`)); controller.setRoot(loaded.root.path); controller.setDetectedPlan(loaded.root.path, plan);
  invalidates(() => controller.setPreset("novel")); invalidates(() => controller.setRole(plan.find((item) => item.kind === "folder")!.path, "transparent")); invalidates(() => controller.setIncluded(plan.find((item) => item.kind === "note")!.path, false)); invalidates(() => controller.moveItem(plan.find((item) => item.kind === "note")!.path, 1)); invalidates(() => controller.setBodyAliases(["Body"])); invalidates(() => controller.setMatter("front", false)); invalidates(() => controller.setFormatting({ fontSize: 11 })); invalidates(() => controller.setTableOfContents(true)); invalidates(() => controller.setVariable("BookTitle", "Changed")); invalidates(() => controller.setOutput("Other Exports", "Changed.docx"));
  controller.state.preparedSession = prepared; controller.setDownloadAfterExport(false); assert.equal(controller.state.preparedSession, prepared);
});

test("workspace controller deduplicates preparation/export and cancels on close", async () => {
  const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const request = preparedRequest(loaded.root.path, plan); const prepared = await new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250).prepare(request, plan); let prepares = 0; let exports = 0; let resolvePrepare!: (session: typeof prepared) => void;
  const controller = new CompileWorkspaceController(request, request.formatting!, { prepare: (_request, _plan, signal) => { prepares += 1; return new Promise((resolve, reject) => { resolvePrepare = resolve; signal.addEventListener("abort", () => reject(new CompilationCancelledError()), { once: true }); }); }, sessionIsCurrent: async () => true, export: async () => { exports += 1; } }); controller.setDetectedPlan(loaded.root.path, plan);
  const first = controller.prepare(); const second = controller.prepare(); assert.equal(first, second); assert.equal(prepares, 1); resolvePrepare(prepared); await first; controller.state.preparedSession = prepared;
  const exportOne = controller.export(); const exportTwo = controller.export(); assert.equal(exportOne, exportTwo); await exportOne; assert.equal(exports, 1);
  const cancelling = new CompileWorkspaceController(request, request.formatting!, { prepare: (_request, _plan, signal) => new Promise((_resolve, reject) => signal.addEventListener("abort", () => reject(new CompilationCancelledError()), { once: true })), sessionIsCurrent: async () => true, export: async () => undefined }); cancelling.setDetectedPlan(loaded.root.path, plan); const pending = cancelling.prepare(); cancelling.close(); await pending; assert.equal(cancelling.state.preparedSession, undefined);
});

test("operation cancellation retains its lock until settled and finalisation disables cancellation", () => { const operations = new OperationStateController(); const operation = operations.begin("exporting")!; assert.equal(operation.cancel(), true); assert.equal(operations.begin("exporting"), undefined); operation.settle(); const next = operations.begin("exporting")!; next.finalise(); assert.equal(next.cancel(), false); next.complete(); assert.equal(operations.busy, false); });

test("content-tree helpers preserve child choices and authoritative sibling order", () => { const root = "Book"; const plan = [{ path: "Book/Manuscript", parentPath: root, name: "Manuscript", kind: "folder", role: "transparent", included: true, order: 0 }, { path: "Book/Manuscript/A.md", parentPath: "Book/Manuscript", name: "A", kind: "note", role: "scene", included: false, order: 0 }, { path: "Book/Manuscript/B.md", parentPath: "Book/Manuscript", name: "B", kind: "note", role: "scene", included: true, order: 1 }] as never; const controller = new CompileWorkspaceController(preparedRequest(root, plan), preparedRequest(root, plan).formatting!, { prepare: async () => { throw new Error(); }, sessionIsCurrent: async () => true, export: async () => undefined }); controller.setDetectedPlan(root, plan); controller.setIncluded("Book/Manuscript", false); controller.setIncluded("Book/Manuscript", true); assert.equal(plan[1].included, false); assert.equal(plan[2].included, true); assert.equal(isEffectivelyIncluded(plan[2], plan, root), true); const moved = moveSibling(plan, root, plan[2].path, -1); assert.equal(moved.find((item) => item.path === plan[2].path)?.order, 0); });

test("export preview view model references the exact prepared Book", async () => { const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const session = await new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250).prepare(preparedRequest(loaded.root.path, plan), plan); const view = buildExportPreviewViewModel(session); assert.equal(view.book, session.book); assert.equal(createPreparedExportRequest(session, session.outputPaths[0], false).book, view.book); assert.deepEqual(view.parts.map((part) => part.chapters.map((chapter) => chapter.sceneCount)), [[2], [1]]); });

test("history service records success only after requested and distinguishes failure/cancellation", async () => { const settings = { ...DEFAULT_SETTINGS, exportHistory: [], compileLogs: [], maximumExportHistoryEntries: 10, enableCompileLogs: true }; let saves = 0; const history = new CompileHistoryService(() => settings, async () => { saves += 1; }, "0.9.1"); const record = { timestamp: new Date("2026-01-01"), started: Date.now(), profile: "Test", manuscript: "Book", format: "docx" as const, outputFiles: ["Exports/Book.docx"] }; assert.equal(history.getHistory().length, 0); await history.recordFailure({ ...record, message: "failed" }); await history.recordCancellation(record); await history.recordSuccess(record); assert.deepEqual(history.getHistory().map((item) => [item.success, item.cancelled]), [[true, undefined], [false, true], [false, undefined]]); assert.equal(saves, 3); });

test("failed results expose no platform result actions", () => { const actions = new ResultActionService({ vault: { adapter: {} } } as never); assert.deepEqual(actions.capabilities("Exports/Book.docx", false), { open: false, reveal: false, saveCopy: false }); });

test("stale prepared source keeps the workspace openable for Refresh Preview", async () => { const loaded = await loadFixtureTree("samples/Book 1 - Warden of Silence"); const plan = await classifyContentPlan(loaded.vault as never, createContentPlan(loaded.root, "novel-parts")); const request = preparedRequest(loaded.root.path, plan); const session = await new CompilePreparationService(loaded.vault as never, createDefaultProfiles()[1], 250).prepare(request, plan); let exports = 0; const controller = new CompileWorkspaceController(request, request.formatting!, { prepare: async () => session, sessionIsCurrent: async () => false, export: async () => { exports += 1; } }); controller.setDetectedPlan(loaded.root.path, plan); controller.state.preparedSession = session; assert.equal(await controller.export(), false); assert.equal(exports, 0); assert.equal(controller.state.preparedSession, undefined); assert.match(controller.state.error?.message ?? "", /Refresh the preview/i); });

test("main delegates orchestration and ExportCoordinator is the sole exporter owner", async () => { const mainSource = await readFile(path.join("src", "main.ts"), "utf8"); const coordinatorSource = await readFile(path.join("src", "export-coordinator.ts"), "utf8"); const otherProduction = (await Promise.all(["compile-command-service.ts", "compile-modal.ts", "validation.ts"].map((file) => readFile(path.join("src", file), "utf8")))).join("\n"); assert.doesNotMatch(mainSource, /new (DocxExporter|MarkdownExporter)|recordSuccess\(|recordFailure\(|calculateSourceFingerprint/); assert.match(mainSource, /new ExportCoordinator/); assert.match(coordinatorSource, /exportPreparedSession\(session: PreparedCompileSession/); assert.match(coordinatorSource, /new DocxExporter/); assert.doesNotMatch(otherProduction, /new DocxExporter/); assert.doesNotMatch(coordinatorSource, /ScannedBook/); });

test("0.9.2 production source has one preparation/export route and no external execution, network, telemetry, or plugin API access", async () => {
  const files = await sourceFiles("src"); const entries = await Promise.all(files.map(async (file) => [file, await readFile(file, "utf8")] as const)); const source = entries.map(([, content]) => content).join("\n");
  assert.deepEqual(entries.filter(([, content]) => /new VaultScanner\(/.test(content)).map(([file]) => file), [path.join("src", "compile-preparation.ts")]);
  assert.deepEqual(entries.filter(([, content]) => /new ExportCoordinator\(/.test(content)).map(([file]) => file), [path.join("src", "main.ts")]);
  assert.doesNotMatch(source, /from\s+["'](?:node:)?child_process["']|\b(?:execFile|execSync|spawnSync)\s*\(/);
  assert.doesNotMatch(source, /\bfetch\s*\(|XMLHttpRequest|new\s+WebSocket|sendBeacon|telemetry|plugins\.getPlugin|app\.plugins/);
  assert.doesNotMatch(source, /createDocx\s*\(/);
  assert.deepEqual(entries.filter(([, content]) => /pandoc/i.test(content)).map(([file]) => file).sort(), ["src/compile-history.ts", "src/diagnostics.ts", "src/profiles.ts", "src/settings.ts", "src/simple-workflow.ts"]);
});

test("0.9.2 version metadata and release package allowlist are consistent", async () => { const manifest = JSON.parse(await readFile("manifest.json", "utf8")); const packageJson = JSON.parse(await readFile("package.json", "utf8")); const lock = JSON.parse(await readFile("package-lock.json", "utf8")); const versions = JSON.parse(await readFile("versions.json", "utf8")); const packaging = await readFile(path.join("scripts", "package.mjs"), "utf8"); assert.equal(manifest.version, "0.9.2"); assert.equal(packageJson.version, manifest.version); assert.equal(lock.version, manifest.version); assert.equal(lock.packages[""].version, manifest.version); assert.equal(versions[manifest.version], manifest.minAppVersion); assert.match(packaging, /const required = \["main\.js", "manifest\.json", "styles\.css"\]/); assert.doesNotMatch(packaging, /data\.json|node_modules|\.test-build/); });

let failures = 0;
for (const [name, action] of tests) { try { await action(); process.stdout.write(`✓ ${name}\n`); } catch (error) { failures += 1; process.stderr.write(`✗ ${name}\n${error instanceof Error ? error.stack : String(error)}\n`); } }
if (failures) process.exitCode = 1; else process.stdout.write(`${tests.length} tests passed.\n`);
