import { Setting } from "obsidian";
import type { DocxStylePreset, StructuralDisplay } from "../settings";
import type { CompileWorkspaceController } from "./compile-workspace-controller";

export function renderFormattingStep(container: HTMLElement, controller: CompileWorkspaceController, tableOfContents: boolean, setTableOfContents: (value: boolean) => void): void {
  const { formatting, request } = controller.state;
  container.createEl("h2", { text: "Format your DOCX" }); container.createEl("p", { text: "These choices affect the generated Word document only. Your Markdown notes are never changed." });
  new Setting(container).setName("Document style").addDropdown((dropdown) => dropdown.addOption("vellum", "Vellum-ready manuscript").addOption("standard", "Standard manuscript").setValue(request.docxPreset).onChange((value) => controller.setDocxPreset(value as DocxStylePreset)));
  new Setting(container).setName("Font").addDropdown((dropdown) => dropdown.addOption("Times New Roman", "Times New Roman").addOption("Garamond", "Garamond").addOption("Georgia", "Georgia").addOption("Arial", "Arial").setValue(formatting.font).onChange((font) => controller.setFormatting({ font })));
  new Setting(container).setName("Font size").addDropdown((dropdown) => dropdown.addOption("11", "11 pt").addOption("12", "12 pt").addOption("13", "13 pt").setValue(String(formatting.fontSize)).onChange((value) => controller.setFormatting({ fontSize: Number(value) })));
  new Setting(container).setName("Line spacing").addDropdown((dropdown) => dropdown.addOption("1", "Single").addOption("1.15", "1.15").addOption("1.5", "1.5 lines").addOption("2", "Double").setValue(String(formatting.lineSpacing)).onChange((value) => controller.setFormatting({ lineSpacing: Number(value) })));
  new Setting(container).setName("First-line indent").addDropdown((dropdown) => dropdown.addOption("0", "None").addOption("0.25", "0.25 in").addOption("0.5", "0.5 in").setValue(String(formatting.firstLineIndent)).onChange((value) => controller.setFormatting({ firstLineIndent: Number(value) })));
  new Setting(container).setName("Page size").addDropdown((dropdown) => dropdown.addOption("letter", "US Letter").addOption("a4", "A4").setValue(formatting.pageSize).onChange((value) => controller.setFormatting({ pageSize: value === "a4" ? "a4" : "letter" })));
  new Setting(container).setName("Start chapters on a new page").addToggle((toggle) => toggle.setValue(formatting.chapterPageBreak).onChange((chapterPageBreak) => controller.setFormatting({ chapterPageBreak })));
  new Setting(container).setName("Add a title page").setDesc("Uses the book title and author entered on the Export step.").addToggle((toggle) => toggle.setValue(formatting.titlePage).onChange((titlePage) => controller.setFormatting({ titlePage })));
  new Setting(container).setName("Scene breaks").addDropdown((dropdown) => dropdown.addOption("#", "Centered * * *").addOption("***", "Three asterisks").addOption("", "Blank space only").setValue(request.custom?.sceneSeparator ?? "#").onChange((value) => controller.setSceneSeparator(value)));
  displayChoice(container, "Part headings", request.partDisplay ?? "word-title", (value) => controller.setDisplay("part", value)); displayChoice(container, "Chapter headings", request.chapterDisplay ?? "word-title", (value) => controller.setDisplay("chapter", value));
  new Setting(container).setName("Include table of contents").setDesc("Word will populate the table when fields are updated.").addToggle((toggle) => toggle.setValue(tableOfContents).onChange((value) => { setTableOfContents(value); controller.notifyExternalModelChange(); }));
  const advanced = container.createEl("details"); advanced.createEl("summary", { text: "Advanced options" }); new Setting(advanced).setName("Manuscript body headings").setDesc("If a note contains one of these headings, only that section is exported.").addText((text) => text.setValue(request.custom?.bodySectionAliases?.join(", ") ?? "Scene, Manuscript, Text, Draft, Body").onChange((value) => controller.setBodyAliases(value.split(",").map((item) => item.trim()).filter(Boolean))));
}
function displayChoice(container: HTMLElement, name: string, current: StructuralDisplay, change: (value: StructuralDisplay) => void): void { const kind = name.startsWith("Part") ? "Part" : "Chapter"; new Setting(container).setName(name).addDropdown((dropdown) => dropdown.addOption("word", `${kind} One`).addOption("numeric", `${kind} 1`).addOption("word-title", `${kind} One — Title`).addOption("numeric-title", `${kind} 1 — Title`).addOption("title", "Title only").addOption("custom", "Custom template").setValue(current).onChange((value) => change(value as StructuralDisplay))); }
