/** Structural validators run before browser download dispatch. */
import { strFromU8, unzipSync } from "fflate";
import { validateDocxBytes } from "./docx-validator";
import type { ExportFormat, ExportValidationResult, ExportValidator } from "./export-types";
import { inspectNativePdfTextLines, measureNativePdfText, recoverNativePdfText } from "./native-pdf";

const valid = (): ExportValidationResult => ({ valid: true, errors: [] });
const invalid = (...errors: string[]): ExportValidationResult => ({ valid: false, errors });
const decode = (bytes: Uint8Array): string => new TextDecoder("utf-8", { fatal: false }).decode(bytes);

class DocxValidator implements ExportValidator { validate(bytes: Uint8Array): ExportValidationResult { return validateDocxBytes(bytes); } }
class OdtValidator implements ExportValidator {
  validate(bytes: Uint8Array): ExportValidationResult { try { const files = unzipSync(bytes); const required = ["mimetype", "META-INF/manifest.xml", "content.xml", "styles.xml", "meta.xml", "settings.xml"]; const missing = required.filter((name) => !files[name]); if (missing.length) return invalid(`Missing ODT entries: ${missing.join(", ")}`); if (strFromU8(files.mimetype) !== "application/vnd.oasis.opendocument.text") return invalid("ODT mimetype is invalid."); if (firstZipEntry(bytes) !== "mimetype" || !firstZipEntryStored(bytes)) return invalid("ODT mimetype must be the first uncompressed package entry."); const manifest = strFromU8(files["META-INF/manifest.xml"]); for (const match of manifest.matchAll(/manifest:full-path="([^"]+)"/g)) if (match[1] !== "/" && !files[match[1]]) return invalid(`ODT manifest target ${match[1]} is missing.`); const content = strFromU8(files["content.xml"]); const styles = strFromU8(files["styles.xml"]); if (![manifest, content, styles, strFromU8(files["meta.xml"]), strFromU8(files["settings.xml"])].every(wellFormedXml)) return invalid("ODT contains malformed XML."); if (!/<office:text>[\s\S]*<text:p/.test(content)) return invalid("ODT has no text body."); for (const style of requiredStyles) if (!styles.includes(`style:name="${style}"`)) return invalid(`ODT style ${style} is missing.`); return valid(); } catch { return invalid("ODT is not a readable ZIP package."); } }
}
class PdfValidator implements ExportValidator {
  validate(bytes: Uint8Array): ExportValidationResult {
    const text = new TextDecoder("latin1").decode(bytes); const errors: string[] = [];
    if (!text.startsWith("%PDF-")) errors.push("PDF header is missing.");
    if (bytes.length < 500) errors.push("PDF is unexpectedly small.");
    if (!/\/Type \/Catalog\b/.test(text)) errors.push("PDF Catalog is missing.");
    if (!/\/Type \/Pages\b/.test(text)) errors.push("PDF Pages tree is missing.");
    if ((text.match(/\/Type \/Page\b/g) ?? []).length < 1) errors.push("PDF contains no pages.");
    if (!/\/Resources\s*<<[\s\S]*?\/Font\s*<</.test(text) || !/\/Subtype \/Type1\b/.test(text)) errors.push("PDF font resource is missing or unsupported.");
    if (!/\/Encoding \/WinAnsiEncoding\b/.test(text)) errors.push("PDF font encoding is missing.");
    if (!/\/ToUnicode\s+\d+\s+0\s+R/.test(text) || !/begincmap[\s\S]*beginbfchar[\s\S]*endcmap/.test(text)) errors.push("PDF ToUnicode mapping is missing.");
    if (!/\/Contents\s+\d+\s+0\s+R/.test(text) || !/stream\n[\s\S]*?\bBT\b[\s\S]*?\bTj\b[\s\S]*?endstream/.test(text)) errors.push("PDF content stream is missing.");
    if (/\/CIDToGIDMap \/Identity|\/Encoding \/Identity-H/.test(text)) errors.push("PDF uses an unsafe identity glyph mapping without an embedded font.");
    if (/\([^\r\n)]*[\x80-\xFF][^\r\n)]*\)\s*Tj/.test(text)) errors.push("PDF contains non-ASCII bytes in a literal text string.");
    for (const match of text.matchAll(/<([0-9A-F]*)>\s*Tj/g)) if (match[1].length % 2 !== 0) errors.push("PDF contains an odd-length hexadecimal text string.");
    if (!recoverNativePdfText(bytes).trim()) errors.push("PDF text cannot be recovered through ToUnicode.");
    const media = /\/MediaBox \[0 0 ([\d.]+) ([\d.]+)\]/.exec(text); const layout = /\/MCLayout << \/LeftMargin ([\d.]+) \/RightMargin ([\d.]+) \/TopMargin ([\d.]+) \/BottomMargin ([\d.]+) \/UsableWidth ([\d.]+) >>/.exec(text);
    if (!media || !layout) errors.push("PDF page or layout dimensions are missing.");
    else {
      const pageWidth = Number(media[1]); const pageHeight = Number(media[2]); const left = Number(layout[1]); const right = Number(layout[2]); const top = Number(layout[3]); const bottom = Number(layout[4]); const usable = Number(layout[5]);
      const knownPage = Math.abs(pageWidth - 595.28) < 0.1 && Math.abs(pageHeight - 841.89) < 0.1 || Math.abs(pageWidth - 612) < 0.1 && Math.abs(pageHeight - 792) < 0.1; if (!knownPage) errors.push("PDF page dimensions are not A4 or Letter points.");
      if (left < 18 || right < 18 || top < 18 || bottom < 18 || left > pageWidth / 3 || right > pageWidth / 3) errors.push("PDF margins are outside plausible bounds.");
      if (Math.abs(usable - (pageWidth - left - right)) > 0.1 || usable < pageWidth * 0.6) errors.push("PDF usable text width is invalid or implausibly narrow.");
      const font = /\/BaseFont \/(Times-Roman|Helvetica)/.exec(text)?.[1] as "Times-Roman" | "Helvetica" | undefined; const lines = inspectNativePdfTextLines(bytes); const textOperatorCount = (text.match(/\bTj\b/g) ?? []).length; if (!font || !lines.length || lines.length !== textOperatorCount) errors.push("PDF text matrices cannot be inspected.");
      else for (const line of lines) { const measured = measureNativePdfText(line.text, font, line.size, line.bold); if (line.size < 6 || line.size > 72 || line.leading <= 0 || line.leading < line.size * 0.8 || line.leading > line.size * 4) errors.push("PDF font size or leading is implausible."); if (line.x < left - 0.2 || line.x + measured > pageWidth - right + 0.5) errors.push("PDF text falls outside the horizontal margins."); if (line.y < bottom - 0.2 || line.y > pageHeight - top + 0.2) errors.push("PDF text falls outside the vertical margins."); }
    }
    for (const match of text.matchAll(/<< \/Length (\d+) >>\nstream\n/g)) { const start = match.index + match[0].length; const end = start + Number(match[1]); if (text.slice(end, end + 10) !== "\nendstream") errors.push("PDF stream length does not match its byte payload."); }
    const xref = /xref\n0 (\d+)\n0000000000 65535 f \n([\s\S]*?)\ntrailer/.exec(text); if (xref) { const entries = xref[2].split("\n"); if (entries.length !== Number(xref[1]) - 1) errors.push("PDF cross-reference entry count is invalid."); entries.forEach((entry, index) => { const offset = Number(entry.slice(0, 10)); if (!Number.isInteger(offset) || !text.startsWith(`${index + 1} 0 obj\n`, offset)) errors.push("PDF cross-reference offset is invalid."); }); } else errors.push("PDF cross-reference table is missing.");
    const start = /startxref\s+(\d+)\s+%%EOF\s*$/.exec(text); if (!start || text.slice(Number(start[1]), Number(start[1]) + 4) !== "xref") errors.push("PDF startxref does not point to the cross-reference table.");
    return errors.length ? invalid(...new Set(errors)) : valid();
  }
}
class EpubValidator implements ExportValidator {
  validate(bytes: Uint8Array): ExportValidationResult { try { const files = unzipSync(bytes); if (firstZipEntry(bytes) !== "mimetype" || !firstZipEntryStored(bytes) || strFromU8(files.mimetype ?? new Uint8Array()) !== "application/epub+zip") return invalid("EPUB mimetype is invalid, compressed, or misplaced."); for (const name of ["META-INF/container.xml", "OEBPS/content.opf", "OEBPS/nav.xhtml", "OEBPS/style.css"]) if (!files[name]) return invalid(`EPUB entry ${name} is missing.`); const container = strFromU8(files["META-INF/container.xml"]); if (!wellFormedXml(container) || !container.includes(`full-path="OEBPS/content.opf"`)) return invalid("EPUB container rootfile is invalid."); const opf = strFromU8(files["OEBPS/content.opf"]); if (!wellFormedXml(opf)) return invalid("EPUB package document is malformed."); const ids = new Set([...opf.matchAll(/<item\s+id="([^"]+)"[^>]*href="([^"]+)"/g)].map((match) => match[1])); for (const match of opf.matchAll(/<item\s+id="[^"]+"[^>]*href="([^"]+)"/g)) if (!files[`OEBPS/${match[1]}`]) return invalid(`EPUB manifest target ${match[1]} is missing.`); for (const match of opf.matchAll(/<itemref\s+idref="([^"]+)"/g)) if (!ids.has(match[1])) return invalid(`EPUB spine reference ${match[1]} is invalid.`); const xhtmlEntries = Object.entries(files).filter(([name]) => name.endsWith(".xhtml")); const xhtml = xhtmlEntries.map(([, value]) => strFromU8(value)).join("\n"); if (!xhtmlEntries.every(([, value]) => wellFormedXml(strFromU8(value)))) return invalid("EPUB XHTML is malformed."); for (const match of xhtml.matchAll(/(?:src|href)=["']([^"'#]+)(?:#[^"']*)?["']/gi)) if (!/^[a-z]+:/i.test(match[1]) && !files[`OEBPS/${match[1]}`]) return invalid(`EPUB internal reference ${match[1]} is missing.`); if (/<script\b|(?:src|href)=["']https?:|url\(\s*https?:/i.test(xhtml)) return invalid("EPUB contains scripts or remote resources."); return valid(); } catch { return invalid("EPUB is not a readable ZIP package."); } }
}
class HtmlValidator implements ExportValidator { validate(bytes: Uint8Array): ExportValidationResult { const text = decode(bytes); if (!/^<!doctype html>/i.test(text) || !/<html\b[\s\S]*<head\b[\s\S]*<body\b/i.test(text)) return invalid("HTML document structure is incomplete."); if (!/<meta charset="utf-8">/i.test(text) || !/<title>[^<]+<\/title>/i.test(text) || !/<main>[\s\S]*<section\b/.test(text)) return invalid("HTML metadata or manuscript content is missing."); if (/<script\b|(?:src|href)=["']https?:|url\(\s*https?:/i.test(text)) return invalid("HTML contains scripts or remote resources."); return valid(); } }
class XmlValidator implements ExportValidator { validate(bytes: Uint8Array): ExportValidationResult { const text = decode(bytes); if (!text.startsWith(`<?xml version="1.0" encoding="UTF-8"?>`)) return invalid("XML declaration is missing."); if (!wellFormedXml(text)) return invalid("XML element nesting is malformed."); if (!/<manuscript xmlns="https:\/\/manuscript-compiler\.dev\/schema" schemaVersion="1\.0">/.test(text)) return invalid("XML namespace or schema version is invalid."); if (!/<metadata>[\s\S]*<title>[\s\S]*<frontMatter>[\s\S]*<body>[\s\S]*<backMatter>/.test(text)) return invalid("XML manuscript hierarchy is incomplete."); if (/(?:file|vault|profile)Path=|<settings>|<profileId>/i.test(text)) return invalid("XML contains compiler-internal data."); return valid(); } }

const requiredStyles = ["Title", "Author", "FrontMatterHeading", "BackMatterHeading", "PartNumber", "PartTitle", "ChapterNumber", "ChapterTitle", "FirstParagraph", "BodyText", "SceneBreak"];
export const EXPORT_VALIDATORS: Record<ExportFormat, ExportValidator> = { docx: new DocxValidator(), odt: new OdtValidator(), pdf: new PdfValidator(), epub: new EpubValidator(), html: new HtmlValidator(), xml: new XmlValidator() };

function firstZipEntry(bytes: Uint8Array): string { if (bytes.length < 30 || bytes[0] !== 0x50 || bytes[1] !== 0x4b || bytes[2] !== 0x03 || bytes[3] !== 0x04) return ""; const length = bytes[26] | bytes[27] << 8; return new TextDecoder().decode(bytes.slice(30, 30 + length)); }
function firstZipEntryStored(bytes: Uint8Array): boolean { return bytes.length >= 10 && bytes[8] === 0 && bytes[9] === 0; }
function wellFormedXml(value: string): boolean { const stack: string[] = []; for (const match of value.matchAll(/<([^!?][^>]*?)>/g)) { const token = match[1].trim(); if (!token || token.endsWith("/")) continue; if (token.startsWith("/")) { if (stack.pop() !== token.slice(1).trim()) return false; } else stack.push(token.split(/\s/, 1)[0]); } return stack.length === 0; }
