import { App, FuzzySuggestModal, Modal, Notice, PluginSettingTab, Setting, TextAreaComponent, TFolder } from "obsidian";
import type ManuscriptCompilerPlugin from "./main";
import type { Chapter, CompilePreview, CompileResult, CompileWarning, ManuscriptDocument, Part } from "./model";
import { duplicateProfile, validateProfile } from "./profiles";
import type { CompileProfile, DocxStylePreset, StructurePreset } from "./settings";
import { documentWordCount } from "./statistics";
import { STRUCTURE_PRESET_NAMES } from "./simple-workflow";
import type { ValidationResult } from "./validation";
import { ProfileWizardModal } from "./wizards";

export class FolderSuggestModal extends FuzzySuggestModal<TFolder> {
  constructor(app: App, private readonly onChoose: (folder: TFolder) => void) { super(app); }
  getItems(): TFolder[] { return this.app.vault.getAllLoadedFiles().filter((file): file is TFolder => file instanceof TFolder && file.path !== "/"); }
  getItemText(folder: TFolder): string { return folder.path; }
  onChooseItem(folder: TFolder): void { this.onChoose(folder); }
}

export class CompilePreviewModal extends Modal {
  constructor(app: App, private readonly preview: CompilePreview, private readonly expanded: boolean, private readonly showStatistics: boolean, private readonly resolve: (compile: boolean) => void) { super(app); }
  onOpen(): void {
    this.modalEl.addClass("manuscript-compiler-preview"); this.titleEl.setText("Compile preview");
    const summary = this.contentEl.createEl("dl", { cls: "manuscript-compiler-report" });
    [["Manuscript folder", this.preview.book.root.path], ["Parts", String(this.preview.parts)], ["Chapters", String(this.preview.chapters)], ["Scenes", String(this.preview.scenes)], ["Front matter", String(this.preview.frontMatter)], ["Back matter", String(this.preview.backMatter)], ["Words", this.preview.wordCount.toLocaleString()], ["Output", this.preview.outputPaths.join(", ")]].forEach(([label, value]) => row(summary, label, value));
    const important = this.preview.issues.filter((issue) => issue.severity !== "information");
    if (important.length) { this.contentEl.createEl("h3", { text: "Important warnings" }); const list = this.contentEl.createEl("ul"); important.forEach((issue) => list.createEl("li", { text: issue.message })); }
    const details = this.contentEl.createEl("details"); details.createEl("summary", { text: "Details" });
    const controls = new Setting(details).setName("Find chapters or scenes"); controls.addSearch((search) => search.setPlaceholder("Search structure…").onChange((value) => this.filterTree(value))); controls.addButton((button) => button.setButtonText("Expand all").onClick(() => this.setTreeExpanded(true))).addButton((button) => button.setButtonText("Collapse all").onClick(() => this.setTreeExpanded(false)));
    const layout = details.createDiv({ cls: "manuscript-compiler-preview-layout" }); const tree = layout.createDiv({ cls: "manuscript-compiler-tree" }); const inspector = layout.createDiv({ cls: "manuscript-compiler-inspector" }); inspector.createEl("p", { text: "Select a scene to inspect its filename, word count, metadata, and compile status." });
    const root = this.branch(tree, this.preview.book.title, true, this.statusForPath(this.preview.book.root.path)); this.documentBranch(root, "📄 Front Matter", this.preview.book.frontMatter.documents, inspector); this.preview.book.parts.forEach((part) => this.partBranch(root, part, inspector)); this.preview.book.orphanScenes.forEach((scene) => this.sceneNode(root, scene, inspector)); this.documentBranch(root, "📄 Back Matter", this.preview.book.backMatter.documents, inspector);
    if (this.showStatistics) { const stats = details.createEl("dl", { cls: "manuscript-compiler-report" }); row(stats, "Average chapter", `${this.preview.statistics.averageChapterLength.toLocaleString()} words`); row(stats, "Average scene", `${this.preview.statistics.averageSceneLength.toLocaleString()} words`); row(stats, "Reading time", `${this.preview.statistics.readingTimeMinutes} min`); }
    this.renderIssues(details, this.preview.issues);
    new Setting(this.contentEl).addButton((button) => button.setButtonText("Cancel").onClick(() => { this.resolve(false); this.close(); })).addButton((button) => button.setButtonText(this.preview.canExport ? "Compile" : "Export unavailable").setCta().setDisabled(!this.preview.canExport).onClick(() => { this.resolve(true); this.close(); }));
  }
  onClose(): void { this.contentEl.empty(); }
  private branch(parent: HTMLElement, label: string, root = false, status = "included"): HTMLElement { const details = parent.createEl("details"); details.dataset.search = label.toLowerCase(); details.open = root || this.expanded; const summary = details.createEl("summary"); summary.createSpan({ cls: `manuscript-status manuscript-status-${status}`, text: status === "included" ? "✓" : status === "excluded" ? "−" : "!" }); summary.createSpan({ text: `${label} — ${status}` }); return details.createDiv({ cls: "manuscript-tree-children" }); }
  private documentBranch(parent: HTMLElement, label: string, documents: ManuscriptDocument[], inspector: HTMLElement): void { const branch = this.branch(parent, label, false, documents.some((item) => item.excluded) ? "warning" : "included"); documents.forEach((document) => this.sceneNode(branch, document, inspector)); }
  private partBranch(parent: HTMLElement, part: Part, inspector: HTMLElement): void { if (part.synthetic) { part.orphanScenes.forEach((scene) => this.sceneNode(parent, scene, inspector)); part.chapters.forEach((chapter) => this.chapterBranch(parent, chapter, inspector)); return; } const branch = this.branch(parent, `📚 ${part.title}`, false, this.statusForPath(part.path)); part.orphanScenes.forEach((scene) => this.sceneNode(branch, scene, inspector)); part.chapters.forEach((chapter) => this.chapterBranch(branch, chapter, inspector)); }
  private chapterBranch(parent: HTMLElement, chapter: Chapter, inspector: HTMLElement): void { const branch = this.branch(parent, `📖 ${chapter.title}`, false, this.statusForPath(chapter.path)); chapter.scenes.forEach((scene) => this.sceneNode(branch, scene, inspector)); }
  private sceneNode(parent: HTMLElement, document: ManuscriptDocument, inspector: HTMLElement): void { const status = document.excluded ? "excluded" : this.statusForPath(document.file.path); const row = parent.createDiv({ cls: "manuscript-tree-scene" }); row.dataset.search = document.title.toLowerCase(); row.createSpan({ cls: `manuscript-status manuscript-status-${status}`, text: status === "included" ? "✓" : status === "excluded" ? "−" : "!" }); const button = row.createEl("button", { cls: "clickable-icon manuscript-scene-button", text: `📝 ${document.title} — ${status}` }); button.addEventListener("click", () => this.inspect(document, inspector)); }
  private inspect(document: ManuscriptDocument, inspector: HTMLElement): void { inspector.empty(); inspector.createEl("h3", { text: document.title }); const list = inspector.createEl("dl", { cls: "manuscript-compiler-report" }); row(list, "Filename", document.file.path); row(list, "Word count", documentWordCount(document.content).toLocaleString()); row(list, "Compile status", document.excluded ? `Excluded — ${document.exclusionReason ?? "Profile rule"}` : "Included"); inspector.createEl("h4", { text: "Metadata" }); const values = Object.entries(document.metadata.values); if (!values.length) inspector.createEl("p", { text: "None" }); else { const metadata = inspector.createEl("dl", { cls: "manuscript-compiler-report" }); values.forEach(([key, value]) => row(metadata, key, typeof value === "string" ? value : JSON.stringify(value))); } }
  private statusForPath(path: string): "included" | "warning" { return this.preview.issues.some((issue) => issue.path?.includes(path)) ? "warning" : "included"; }
  private setTreeExpanded(expanded: boolean): void { this.contentEl.querySelectorAll<HTMLDetailsElement>(".manuscript-compiler-tree details").forEach((details) => { details.open = expanded; }); }
  private filterTree(query: string): void { const normalized = query.trim().toLowerCase(); const tree = this.contentEl.querySelector(".manuscript-compiler-tree"); if (!tree) return; tree.querySelectorAll<HTMLElement>("[data-search]").forEach((element) => { element.hidden = normalized.length > 0 && !(element.dataset.search ?? "").includes(normalized); }); if (normalized) tree.querySelectorAll<HTMLDetailsElement>("details").forEach((details) => { if (details.querySelector(":scope [data-search]:not([hidden])")) { details.hidden = false; details.open = true; } }); }
  private renderIssues(parent: HTMLElement, issues: CompileWarning[]): void { const details = parent.createEl("details"); details.createEl("summary", { text: `Issues (${issues.length})` }); const list = details.createEl("ul"); issues.forEach((issue) => list.createEl("li", { text: issue.message })); }
}

export class ConfirmOverwriteModal extends Modal {
  constructor(app: App, private readonly path: string, private readonly resolve: (confirmed: boolean) => void) { super(app); }
  onOpen(): void { this.titleEl.setText("Overwrite manuscript?"); this.contentEl.createEl("p", { text: `The file “${this.path}” already exists. Replace it?` }); new Setting(this.contentEl).addButton((button) => button.setButtonText("Cancel").onClick(() => { this.resolve(false); this.close(); })).addButton((button) => button.setButtonText("Overwrite").setWarning().onClick(() => { this.resolve(true); this.close(); })); }
}

export class CompilationProgressModal extends Modal {
  private statusEl?: HTMLElement; private cancelButton?: HTMLButtonElement; private cancelled = false; private completed = false;
  constructor(app: App, private readonly cancel: () => void) { super(app); }
  onOpen(): void { this.titleEl.setText("Compiling manuscript"); this.statusEl = this.contentEl.createEl("p", { text: "Preparing…" }); this.statusEl.setAttribute("role", "status"); this.statusEl.setAttribute("aria-live", "polite"); new Setting(this.contentEl).addButton((button) => { this.cancelButton = button.buttonEl; button.setButtonText("Cancel compilation").setWarning().onClick(() => { if (this.cancelled) return; this.cancelled = true; button.setDisabled(true).setButtonText("Cancelling…"); this.cancel(); }); }); }
  update(stage: string): void { if (!this.cancelled) this.statusEl?.setText(stage); }
  lock(stage: string): void { this.completed = true; this.statusEl?.setText(stage); if (this.cancelButton) { this.cancelButton.disabled = true; this.cancelButton.setText("Finalising file…"); } }
  finish(): void { this.completed = true; this.close(); }
  onClose(): void { if (!this.completed && !this.cancelled) { this.cancelled = true; this.cancel(); } this.contentEl.empty(); }
}

export class ValidationReportModal extends Modal {
  constructor(app: App, private readonly root: string, private readonly report: ValidationResult) { super(app); }
  onOpen(): void { this.titleEl.setText("Manuscript validation report"); const counts = { information: 0, warning: 0, error: 0 }; this.report.issues.forEach((issue) => { counts[issue.severity] += 1; }); const summary = this.contentEl.createEl("dl", { cls: "manuscript-compiler-report" }); [["Manuscript", this.root], ["Front matter", String(this.report.book.frontMatter.documents.filter((item) => !item.excluded && item.content.trim()).length)], ["Parts", String(this.report.statistics.partCount)], ["Chapters", String(this.report.statistics.chapterCount)], ["Scenes", String(this.report.statistics.sceneCount)], ["Back matter", String(this.report.book.backMatter.documents.filter((item) => !item.excluded && item.content.trim()).length)], ["Excluded items", String(this.report.exclusions.length)], ["Errors", String(counts.error)], ["Warnings", String(counts.warning)], ["Information", String(counts.information)]].forEach(([label, value]) => row(summary, label, value)); if (this.report.exclusions.length) { const excluded = this.contentEl.createEl("details"); excluded.createEl("summary", { text: `Excluded content (${this.report.exclusions.length})` }); const list = excluded.createEl("ul"); this.report.exclusions.forEach((item) => list.createEl("li", { text: `${item.name}: ${item.reason}` })); } const issues = this.contentEl.createEl("ul"); this.report.issues.forEach((issue) => issues.createEl("li", { text: `${issue.message}${issue.suggestion ? ` Suggested fix: ${issue.suggestion}` : ""}` })); new Setting(this.contentEl).addButton((button) => button.setButtonText("Close").setCta().onClick(() => this.close())); }
}

export class CompileReportModal extends Modal {
  constructor(app: App, private readonly output: string, private readonly report: CompileResult, private readonly showStatistics: boolean, private readonly openFile?: () => void, private readonly revealFile?: () => void, private readonly saveCopy?: () => void) { super(app); }
  onOpen(): void { const filename = this.output.split(",")[0].split("/").pop() ?? this.output; this.titleEl.setText("DOCX created successfully"); this.contentEl.createEl("h3", { text: filename }); const list = this.contentEl.createEl("dl", { cls: "manuscript-compiler-report" }); [["Saved to vault", this.output], ["Words", this.report.wordCount.toLocaleString()], ["Chapters", String(this.report.chapters)], ["Scenes", String(this.report.scenes)]].forEach(([label, value]) => row(list, label, value)); const warnings = this.report.issues.filter((issue) => issue.severity !== "information"); if (warnings.length) { this.contentEl.createEl("h3", { text: "Warnings" }); warnings.forEach((issue) => this.contentEl.createEl("p", { cls: `manuscript-issue-${issue.severity}`, text: issue.message })); } if (this.showStatistics) this.contentEl.createEl("p", { text: `Average chapter: ${this.report.statistics.averageChapterLength.toLocaleString()} words · Average scene: ${this.report.statistics.averageSceneLength.toLocaleString()} words` }); const actions = new Setting(this.contentEl); if (this.saveCopy) actions.addButton((button) => button.setButtonText("Save a copy to computer").onClick(this.saveCopy!)); if (this.openFile) actions.addButton((button) => button.setButtonText("Open DOCX").onClick(this.openFile!)); if (this.revealFile) actions.addButton((button) => button.setButtonText("Reveal in file manager").onClick(this.revealFile!)); actions.addButton((button) => button.setButtonText("Close").setCta().onClick(() => this.close())); }
}

export class DiagnosticsReportModal extends Modal {
  constructor(app: App, private readonly report: string, private readonly save: () => Promise<string>) { super(app); }
  onOpen(): void { this.titleEl.setText("Diagnostics report"); this.contentEl.createEl("p", { text: "This report contains configuration and environment information, but no manuscript contents." }); const area = new TextAreaComponent(this.contentEl); area.setValue(this.report); area.inputEl.readOnly = true; area.inputEl.addClass("manuscript-profile-json"); new Setting(this.contentEl).addButton((button) => button.setButtonText("Copy").onClick(async () => { try { await navigator.clipboard.writeText(this.report); new Notice("Diagnostics report copied."); } catch { area.inputEl.focus(); area.inputEl.select(); } })).addButton((button) => button.setButtonText("Save to vault").setCta().onClick(async () => { new Notice(`Diagnostics saved to ${await this.save()}`, 6000); this.close(); })).addButton((button) => button.setButtonText("Close").onClick(() => this.close())); }
}

class ProfileJsonModal extends Modal {
  private value: string;
  constructor(app: App, private readonly mode: "import" | "export", profile: CompileProfile, private readonly done: (value?: string) => void) { super(app); this.value = mode === "export" ? JSON.stringify(profile, null, 2) : ""; }
  onOpen(): void { this.titleEl.setText(`${this.mode === "import" ? "Import" : "Export"} compile profile`); const area = new TextAreaComponent(this.contentEl); area.setValue(this.value).onChange((value) => { this.value = value; }); area.inputEl.addClass("manuscript-profile-json"); new Setting(this.contentEl).addButton((button) => button.setButtonText("Close").onClick(() => this.close())); if (this.mode === "import") new Setting(this.contentEl).addButton((button) => button.setButtonText("Import").setCta().onClick(() => { this.done(this.value); this.close(); })); }
}
class ExportHistoryModal extends Modal { constructor(app: App, private readonly plugin: ManuscriptCompilerPlugin) { super(app); } onOpen(): void { this.titleEl.setText("Export history"); this.plugin.settings.exportHistory.forEach((entry) => { const details = this.contentEl.createEl("details"); details.createEl("summary", { text: `${entry.cancelled ? "—" : entry.success ? "✓" : "✗"} ${new Date(entry.timestamp).toLocaleString()} — ${entry.profile}` }); details.createEl("p", { text: `${entry.manuscript} · ${entry.wordCount.toLocaleString()} words` }); entry.outputFiles.forEach((path) => new Setting(details).setName(path).addButton((button) => button.setButtonText("Open").onClick(() => { void this.plugin.openExport(path); }))); }); new Setting(this.contentEl).addButton((button) => button.setButtonText("Clear history and logs").setWarning().onClick(async () => { await this.plugin.clearHistory(); this.close(); })).addButton((button) => button.setButtonText("Close").onClick(() => this.close())); } }
class CompileLogsModal extends Modal { constructor(app: App, private readonly plugin: ManuscriptCompilerPlugin) { super(app); } onOpen(): void { this.titleEl.setText("Compile logs"); this.plugin.settings.compileLogs.forEach((log) => { const details = this.contentEl.createEl("details"); details.createEl("summary", { text: `${log.cancelled ? "Cancelled" : log.success ? "Success" : "Failure"} — ${new Date(log.timestamp).toLocaleString()} — ${log.profile}` }); const pre = details.createEl("pre"); pre.setText([`Compiler: ${log.compilerVersion}`, `Manuscript: ${log.manuscript}`, `Formats: ${log.exportFormats}`, `Outputs: ${log.outputFiles.join(", ") || "None"}`, `Duration: ${log.durationMs} ms`, `Warnings: ${log.warnings.join(" | ") || "None"}`, log.diagnostics ? `Diagnostics:\n${log.diagnostics}` : ""].filter(Boolean).join("\n")); }); new Setting(this.contentEl).addButton((button) => button.setButtonText("Close").onClick(() => this.close())); } }

export class ManuscriptCompilerSettingTab extends PluginSettingTab {
  constructor(app: App, private readonly plugin: ManuscriptCompilerPlugin) { super(app, plugin); }
  display(): void {
    const container = this.containerEl; const settings = this.plugin.settings; const profile = this.plugin.getActiveProfile(); container.empty(); container.createEl("h2", { text: "Manuscript Compiler" }); container.createEl("p", { text: "Set your usual starting choices here. Select, arrange, preview, and create each book in the compiler." });
    new Setting(container).setName("Compile Manuscript").setDesc("Open the complete four-step manuscript builder.").addButton((button) => button.setButtonText("Open Manuscript Compiler").setCta().onClick(() => this.plugin.openCompiler()));
    container.createEl("h3", { text: "Saved defaults" }); this.text(container, "Manuscript folder", settings.defaultManuscriptFolder, (value) => { settings.defaultManuscriptFolder = value; }); this.text(container, "Export folder", settings.defaultExportFolder, (value) => { settings.defaultExportFolder = value; });
    new Setting(container).setName("Book structure").addDropdown((dropdown) => { Object.entries(STRUCTURE_PRESET_NAMES).forEach(([value, label]) => dropdown.addOption(value, label)); dropdown.setValue(settings.defaultStructurePreset).onChange(async (value) => { settings.defaultStructurePreset = value as StructurePreset; await this.plugin.saveSettings(); }); });
    new Setting(container).setName("DOCX style").addDropdown((dropdown) => dropdown.addOption("vellum", "Vellum-ready").addOption("standard", "Standard manuscript").setValue(settings.defaultDocxStyle).onChange(async (value) => { settings.defaultDocxStyle = value as DocxStylePreset; await this.plugin.saveSettings(); }));
    this.toggle(container, "Warn before overwriting", settings.warnBeforeOverwrite, (value) => { settings.warnBeforeOverwrite = value; }); this.toggle(container, "Open DOCX after compile", settings.openAfterCompile, (value) => { settings.openAfterCompile = value; }); this.toggle(container, "Include title page", settings.includeTitlePageByDefault, (value) => { settings.includeTitlePageByDefault = value; }); this.toggle(container, "Include table of contents", settings.includeTableOfContentsByDefault, (value) => { settings.includeTableOfContentsByDefault = value; });
    const advanced = container.createEl("details"); advanced.createEl("summary", { text: "Advanced settings and compatibility" });
    new Setting(advanced).setName("Active legacy profile").addDropdown((dropdown) => { settings.profiles.forEach((item) => dropdown.addOption(item.id, item.name)); dropdown.setValue(profile.id).onChange(async (id) => { settings.activeProfileId = id; await this.plugin.saveSettings(); this.display(); }); });
    new Setting(advanced).setName("Profile actions").addButton((button) => button.setButtonText("New").onClick(() => new ProfileWizardModal(this.app, this.plugin, async (created) => { settings.profiles.push(created); settings.activeProfileId = created.id; await this.plugin.saveSettings(); this.display(); }).open())).addButton((button) => button.setButtonText("Duplicate").onClick(async () => { const copy = duplicateProfile(profile); settings.profiles.push(copy); settings.activeProfileId = copy.id; await this.plugin.saveSettings(); this.display(); })).addButton((button) => button.setButtonText("Delete").setWarning().setDisabled(settings.profiles.length < 2).onClick(async () => { settings.profiles = settings.profiles.filter((item) => item.id !== profile.id); settings.activeProfileId = settings.profiles[0].id; await this.plugin.saveSettings(); this.display(); }));
    new Setting(advanced).setName("Profile JSON").addButton((button) => button.setButtonText("Export").onClick(() => new ProfileJsonModal(this.app, "export", profile, () => undefined).open())).addButton((button) => button.setButtonText("Import").onClick(() => new ProfileJsonModal(this.app, "import", profile, async (json) => { if (!json) return; const validation = validateProfile(JSON.parse(json)); if (!validation.profile) { new Notice(validation.errors.join(" "), 8000); return; } settings.profiles.push(validation.profile); settings.activeProfileId = validation.profile.id; await this.plugin.saveSettings(); this.display(); }).open()));
    new Setting(advanced).setName("Export records").addButton((button) => button.setButtonText(`History (${settings.exportHistory.length})`).onClick(() => new ExportHistoryModal(this.app, this.plugin).open())).addButton((button) => button.setButtonText(`Logs (${settings.compileLogs.length})`).onClick(() => new CompileLogsModal(this.app, this.plugin).open()));
  }
  private text(parent: HTMLElement, name: string, value: string, change: (value: string) => void): void { new Setting(parent).setName(name).addText((text) => text.setValue(value).onChange(async (next) => { change(next.trim()); await this.plugin.saveSettings(); })); }
  private toggle(parent: HTMLElement, name: string, value: boolean, change: (value: boolean) => void): void { new Setting(parent).setName(name).addToggle((toggle) => toggle.setValue(value).onChange(async (next) => { change(next); await this.plugin.saveSettings(); })); }
}

function row(list: HTMLElement, label: string, value: string): void { list.createEl("dt", { text: label }); list.createEl("dd", { text: value }); }
export function showError(error: unknown): void { const message = error instanceof Error ? error.message : String(error); new Notice(`Manuscript Compiler: ${message}`, 8000); console.error("Manuscript Compiler", error); }
