import { App, FuzzySuggestModal, Modal, Notice, PluginSettingTab, Setting, TextAreaComponent, TFolder } from "obsidian";
import type ManuscriptCompilerPlugin from "./main";
import type { Chapter, CompilePreview, CompileResult, CompileWarning, ManuscriptDocument, Part } from "./model";
import { createDefaultProfiles, duplicateProfile, profileId, validateProfile } from "./profiles";
import { chooseLocalFile } from "./platform-compat";
import { DEFAULT_OPTIONS, type CompileProfile, type MetadataFilterRule, type WarningLevel } from "./settings";
import { documentWordCount } from "./statistics";
import type { ValidationResult } from "./validation";

export class FolderSuggestModal extends FuzzySuggestModal<TFolder> {
  constructor(app: App, private readonly onChoose: (folder: TFolder) => void) { super(app); }
  getItems(): TFolder[] { return this.app.vault.getAllLoadedFiles().filter((file): file is TFolder => file instanceof TFolder && file.path !== "/"); }
  getItemText(folder: TFolder): string { return folder.path; }
  onChooseItem(folder: TFolder): void { this.onChoose(folder); }
}

export class CompilePreviewModal extends Modal {
  constructor(app: App, private readonly preview: CompilePreview, private readonly expanded: boolean, private readonly showStatistics: boolean, private readonly resolve: (compile: boolean) => void) { super(app); }
  onOpen(): void {
    this.modalEl.addClass("manuscript-compiler-preview"); this.titleEl.setText("Compile preview");
    const summary = this.contentEl.createEl("dl", { cls: "manuscript-compiler-report" });
    this.row(summary, "Manuscript root", this.preview.book.root.path); this.row(summary, "Output", this.preview.outputPath);
    this.row(summary, "Output formats", this.preview.outputFormats.join(" + ")); this.row(summary, "Output files", this.preview.outputPaths.join(", "));
    this.row(summary, "Pandoc", this.preview.pandocAvailable ? `Available${this.preview.pandocVersion ? ` (${this.preview.pandocVersion})` : ""}` : this.preview.pandocExplanation ?? "Unavailable");
    this.row(summary, "Reference DOCX", this.preview.referenceDocx || "None"); this.row(summary, "Estimated pages", String(this.preview.estimatedPages)); this.row(summary, "Word count", this.preview.wordCount.toLocaleString());
    const layout = this.contentEl.createDiv({ cls: "manuscript-compiler-preview-layout" });
    const tree = layout.createDiv({ cls: "manuscript-compiler-tree" }); const inspector = layout.createDiv({ cls: "manuscript-compiler-inspector" });
    inspector.createEl("p", { text: "Select a scene to inspect its filename, word count, metadata, and compile status." });
    const root = this.branch(tree, this.preview.book.title, true, this.statusForPath(this.preview.book.root.path));
    this.documentBranch(root, "Front Matter", this.preview.book.frontMatter.documents, inspector);
    this.preview.book.parts.forEach((part) => this.partBranch(root, part, inspector));
    this.preview.book.orphanScenes.forEach((scene) => this.sceneNode(root, scene, inspector));
    this.documentBranch(root, "Back Matter", this.preview.book.backMatter.documents, inspector);
    if (this.showStatistics) this.renderStatistics(this.contentEl, this.preview.statistics);
    this.renderWarnings(this.contentEl, this.preview.issues);
    new Setting(this.contentEl).addButton((button) => button.setButtonText("Cancel").onClick(() => { this.resolve(false); this.close(); })).addButton((button) => { button.setButtonText(this.preview.canExport ? "Compile" : "Export unavailable").setCta().setDisabled(!this.preview.canExport).onClick(() => { this.resolve(true); this.close(); }); });
  }
  private branch(parent: HTMLElement, label: string, root = false, status = "included"): HTMLElement { const details = parent.createEl("details"); details.open = root || this.expanded; const summary = details.createEl("summary"); const marker = summary.createSpan({ cls: `manuscript-status manuscript-status-${status}`, text: status === "included" ? "✓" : status === "excluded" ? "−" : "!" }); marker.setAttribute("aria-hidden", "true"); summary.createSpan({ text: `${label} — ${status}` }); return details.createDiv({ cls: "manuscript-tree-children" }); }
  private documentBranch(parent: HTMLElement, label: string, documents: ManuscriptDocument[], inspector: HTMLElement): void { const branch = this.branch(parent, label, false, documents.some((item) => item.excluded) ? "warning" : "included"); documents.forEach((document) => this.sceneNode(branch, document, inspector)); }
  private partBranch(parent: HTMLElement, part: Part, inspector: HTMLElement): void { const branch = this.branch(parent, part.title, false, this.statusForPath(part.path)); part.orphanScenes.forEach((scene) => this.sceneNode(branch, scene, inspector)); part.chapters.forEach((chapter) => this.chapterBranch(branch, chapter, inspector)); }
  private chapterBranch(parent: HTMLElement, chapter: Chapter, inspector: HTMLElement): void { const branch = this.branch(parent, chapter.title, false, this.statusForPath(chapter.path)); chapter.scenes.forEach((scene) => this.sceneNode(branch, scene, inspector)); }
  private sceneNode(parent: HTMLElement, document: ManuscriptDocument, inspector: HTMLElement): void {
    const row = parent.createDiv({ cls: "manuscript-tree-scene" }); const status = document.excluded ? "excluded" : this.statusForPath(document.file.path);
    const marker = row.createSpan({ cls: `manuscript-status manuscript-status-${status}`, text: status === "included" ? "✓" : status === "excluded" ? "−" : "!" }); marker.setAttribute("aria-hidden", "true");
    const button = row.createEl("button", { cls: "clickable-icon manuscript-scene-button", text: document.title }); button.addEventListener("click", () => this.inspect(document, inspector));
  }
  private inspect(document: ManuscriptDocument, inspector: HTMLElement): void {
    inspector.empty(); inspector.createEl("h3", { text: document.title }); const list = inspector.createEl("dl", { cls: "manuscript-compiler-report" });
    this.row(list, "Filename", document.file.path); this.row(list, "Word count", documentWordCount(document.content).toLocaleString()); this.row(list, "Compile status", document.excluded ? `Excluded — ${document.exclusionReason ?? "Profile rule"}` : "Included");
    inspector.createEl("h4", { text: "Metadata" }); const values = Object.entries(document.metadata.values); if (!values.length) inspector.createEl("p", { text: "None" }); else { const metadata = inspector.createEl("dl", { cls: "manuscript-compiler-report" }); values.forEach(([key, value]) => this.row(metadata, key, typeof value === "string" ? value : JSON.stringify(value))); }
  }
  private statusForPath(path: string): "included" | "warning" { return this.preview.issues.some((issue) => issue.path?.includes(path)) ? "warning" : "included"; }
  private renderStatistics(parent: HTMLElement, stats: CompileResult["statistics"]): void {
    parent.createEl("h3", { text: "Statistics" }); const list = parent.createEl("dl", { cls: "manuscript-compiler-report manuscript-statistics" });
    const named = (value?: { name: string; words: number }): string => value ? `${value.name} (${value.words.toLocaleString()} words)` : "—";
    [["Total words", stats.totalWordCount.toLocaleString()], ["Chapters", String(stats.chapterCount)], ["Scenes", String(stats.sceneCount)], ["Average chapter", `${stats.averageChapterLength.toLocaleString()} words`], ["Average scene", `${stats.averageSceneLength.toLocaleString()} words`], ["Longest chapter", named(stats.longestChapter)], ["Shortest chapter", named(stats.shortestChapter)], ["Longest scene", named(stats.longestScene)], ["Shortest scene", named(stats.shortestScene)], ["Reading time", `${stats.readingTimeMinutes} min`]].forEach(([label, value]) => this.row(list, label, value));
  }
  private renderWarnings(parent: HTMLElement, issues: CompileWarning[]): void {
    parent.createEl("h3", { text: `Issues (${issues.length})` });
    for (const severity of ["error", "warning", "information"] as const) { const matches = issues.filter((issue) => issue.severity === severity); if (!matches.length) continue; const details = parent.createEl("details", { cls: `manuscript-issues manuscript-issues-${severity}` }); details.open = severity !== "information"; details.createEl("summary", { text: `${severity[0].toUpperCase()}${severity.slice(1)} (${matches.length})` }); const list = details.createEl("ul"); matches.forEach((issue) => list.createEl("li", { text: issue.message })); }
  }
  private row(list: HTMLElement, label: string, value: string): void { list.createEl("dt", { text: label }); list.createEl("dd", { text: value }); }
  onClose(): void { this.contentEl.empty(); }
}

export class ConfirmOverwriteModal extends Modal {
  constructor(app: App, private readonly path: string, private readonly resolve: (confirmed: boolean) => void) { super(app); }
  onOpen(): void { this.titleEl.setText("Overwrite manuscript?"); this.contentEl.createEl("p", { text: `The file “${this.path}” already exists. Replace it?` }); new Setting(this.contentEl).addButton((button) => button.setButtonText("Cancel").onClick(() => { this.resolve(false); this.close(); })).addButton((button) => button.setButtonText("Overwrite").setWarning().onClick(() => { this.resolve(true); this.close(); })); }
  onClose(): void { this.contentEl.empty(); }
}

export class ValidationReportModal extends Modal {
  constructor(app: App, private readonly root: string, private readonly report: ValidationResult) { super(app); }
  onOpen(): void { this.titleEl.setText("Manuscript validation report"); const counts = { information: 0, warning: 0, error: 0 }; this.report.issues.forEach((issue) => { counts[issue.severity] += 1; }); const summary = this.contentEl.createEl("dl", { cls: "manuscript-compiler-report" }); [["Manuscript", this.root], ["Files checked", String(this.report.book.includedFiles.length + this.report.book.excludedFiles.length)], ["Errors", String(counts.error)], ["Warnings", String(counts.warning)], ["Information", String(counts.information)], ["Validation duration", `${Math.round(this.report.durationMs)} ms`], ["Pandoc", this.report.pandoc.available ? `Available (${this.report.pandoc.version ?? "version unknown"})` : this.report.pandoc.explanation ?? "Not required"]].forEach(([label, value]) => { summary.createEl("dt", { text: label }); summary.createEl("dd", { text: value }); }); for (const severity of ["error", "warning", "information"] as const) { const issues = this.report.issues.filter((issue) => issue.severity === severity); const section = this.contentEl.createEl("details", { cls: `manuscript-issues manuscript-issues-${severity}` }); section.open = severity !== "information"; section.createEl("summary", { text: `${severity[0].toUpperCase()}${severity.slice(1)} (${issues.length})` }); if (!issues.length) section.createEl("p", { text: "None" }); else { const list = section.createEl("ul"); issues.forEach((issue) => list.createEl("li", { text: `${issue.message}${issue.path ? ` — ${issue.path}` : ""}` })); } } new Setting(this.contentEl).addButton((button) => button.setButtonText("Close").setCta().onClick(() => this.close())); }
}

export class CompileReportModal extends Modal {
  constructor(app: App, private readonly output: string, private readonly report: CompileResult, private readonly showStatistics: boolean) { super(app); }
  onOpen(): void { this.titleEl.setText("Compilation complete"); const list = this.contentEl.createEl("dl", { cls: "manuscript-compiler-report" }); [["Output file", this.output], ["Parts", String(this.report.parts)], ["Chapters", String(this.report.chapters)], ["Scenes", String(this.report.scenes)], ["Word count", this.report.wordCount.toLocaleString()], ["Reading time", `${this.report.readingTimeMinutes} min`]].forEach(([label, value]) => { list.createEl("dt", { text: label }); list.createEl("dd", { text: value }); }); if (this.showStatistics) this.statistics(); this.contentEl.createEl("h3", { text: `Issues (${this.report.issues.length})` }); this.report.issues.forEach((issue) => this.contentEl.createEl("p", { cls: `manuscript-issue-${issue.severity}`, text: `${issue.severity.toUpperCase()}: ${issue.message}` })); }
  private statistics(): void { const stats = this.report.statistics; const section = this.contentEl.createEl("details"); section.createEl("summary", { text: "Detailed statistics" }); const list = section.createEl("ul"); list.createEl("li", { text: `Average chapter: ${stats.averageChapterLength.toLocaleString()} words` }); list.createEl("li", { text: `Average scene: ${stats.averageSceneLength.toLocaleString()} words` }); for (const [label, value] of [["Longest chapter", stats.longestChapter], ["Shortest chapter", stats.shortestChapter], ["Longest scene", stats.longestScene], ["Shortest scene", stats.shortestScene]] as const) list.createEl("li", { text: `${label}: ${value ? `${value.name} (${value.words.toLocaleString()} words)` : "—"}` }); }
}

class TextPromptModal extends Modal {
  private value: string;
  constructor(app: App, private readonly heading: string, initial: string, private readonly done: (value?: string) => void) { super(app); this.value = initial; }
  onOpen(): void { this.titleEl.setText(this.heading); new Setting(this.contentEl).addText((text) => { text.setValue(this.value); text.onChange((value) => { this.value = value; }); text.inputEl.setAttribute("aria-label", this.heading); text.inputEl.focus(); text.inputEl.addEventListener("keydown", (event) => { if (event.key === "Enter") { this.done(this.value.trim()); this.close(); } }); }); new Setting(this.contentEl).addButton((button) => button.setButtonText("Cancel").onClick(() => { this.done(); this.close(); })).addButton((button) => button.setButtonText("Save").setCta().onClick(() => { this.done(this.value.trim()); this.close(); })); }
}
class ProfileJsonModal extends Modal {
  private value: string; constructor(app: App, private readonly mode: "import" | "export", profile: CompileProfile, private readonly done: (value?: string) => void) { super(app); this.value = mode === "export" ? JSON.stringify(profile, null, 2) : ""; }
  onOpen(): void { this.titleEl.setText(`${this.mode === "import" ? "Import" : "Export"} compile profile`); this.contentEl.createEl("p", { text: this.mode === "import" ? "Paste a profile JSON object. It will be validated before saving." : "Copy this JSON to share or back up the profile." }); const area = new TextAreaComponent(this.contentEl); area.setValue(this.value).onChange((value) => { this.value = value; }); area.inputEl.addClass("manuscript-profile-json"); new Setting(this.contentEl).addButton((button) => button.setButtonText("Close").onClick(() => { this.done(); this.close(); })); if (this.mode === "import") new Setting(this.contentEl).addButton((button) => button.setButtonText("Import").setCta().onClick(() => { this.done(this.value); this.close(); })); }
}

class ExportHistoryModal extends Modal {
  constructor(app: App, private readonly plugin: ManuscriptCompilerPlugin) { super(app); }
  onOpen(): void { this.titleEl.setText("Export history"); if (!this.plugin.settings.exportHistory.length) this.contentEl.createEl("p", { text: "No exports have been recorded." }); this.plugin.settings.exportHistory.forEach((entry) => { const details = this.contentEl.createEl("details"); details.createEl("summary", { text: `${entry.success ? "✓" : "✗"} ${new Date(entry.timestamp).toLocaleString()} — ${entry.profile}` }); details.createEl("p", { text: `${entry.manuscript} · ${entry.wordCount.toLocaleString()} words${entry.message ? ` · ${entry.message}` : ""}` }); entry.outputFiles.forEach((path) => new Setting(details).setName(path).addButton((button) => button.setButtonText("Open").onClick(() => { void this.plugin.openExport(path); }))); }); new Setting(this.contentEl).addButton((button) => button.setButtonText("Clear history and logs").setWarning().onClick(async () => { await this.plugin.clearHistory(); this.close(); })).addButton((button) => button.setButtonText("Close").onClick(() => this.close())); }
}
class CompileLogsModal extends Modal {
  constructor(app: App, private readonly plugin: ManuscriptCompilerPlugin) { super(app); }
  onOpen(): void { this.titleEl.setText("Compile logs"); if (!this.plugin.settings.compileLogs.length) this.contentEl.createEl("p", { text: "No compile logs have been recorded." }); this.plugin.settings.compileLogs.forEach((log) => { const details = this.contentEl.createEl("details"); details.createEl("summary", { text: `${log.success ? "Success" : "Failure"} — ${new Date(log.timestamp).toLocaleString()} — ${log.profile}` }); const pre = details.createEl("pre"); pre.setText([`Compiler: ${log.compilerVersion ?? "Pre-0.5 log"}`, `Manuscript: ${log.manuscript}`, `Formats: ${log.exportFormats}`, `Outputs: ${log.outputFiles.join(", ") || "None"}`, `Pandoc: ${log.pandocVersion ?? "Not used"}`, `Duration: ${log.durationMs} ms`, `Scan: ${log.scanDurationMs ?? 0} ms`, `Filters: ${log.filterDurationMs ?? 0} ms`, `Generation: ${log.generationDurationMs ?? 0} ms`, `Export: ${log.exportDurationMs ?? 0} ms`, `Warnings: ${log.warnings.join(" | ") || "None"}`, log.diagnostics ? `Diagnostics:\n${log.diagnostics}` : ""].filter(Boolean).join("\n")); }); new Setting(this.contentEl).addButton((button) => button.setButtonText("Close").onClick(() => this.close())); }
}

export class ManuscriptCompilerSettingTab extends PluginSettingTab {
  constructor(app: App, private readonly plugin: ManuscriptCompilerPlugin) { super(app, plugin); }
  display(): void {
    const c = this.containerEl; c.empty(); const profile = this.plugin.getActiveProfile(); c.createEl("h2", { text: "Compile profiles" });
    new Setting(c).setName("Active profile").addDropdown((dropdown) => { this.plugin.settings.profiles.forEach((item) => dropdown.addOption(item.id, item.name)); dropdown.setValue(profile.id).onChange(async (id) => { this.plugin.settings.activeProfileId = id; await this.plugin.saveSettings(); this.display(); }); });
    new Setting(c).setName("Profile actions").addButton((b) => b.setButtonText("New").onClick(() => this.prompt("New profile name", "New Profile", async (name) => { const created: CompileProfile = { ...DEFAULT_OPTIONS, metadataFilters: [], id: profileId(), name, manuscriptRoot: "", exportFolder: "Manuscript Exports", outputFilename: "{BookTitle} Manuscript.md", variables: { BookTitle: "", Series: "", Author: "" }, exportTarget: this.plugin.settings.defaultExportFormat, referenceDocx: this.plugin.settings.defaultReferenceDocx, pandocMetadataFile: "", additionalPandocArguments: "", generateTableOfContents: false, keepIntermediateMarkdown: this.plugin.settings.keepTemporaryMarkdown }; this.plugin.settings.profiles.push(created); this.plugin.settings.activeProfileId = created.id; await this.saveRefresh(); }))).addButton((b) => b.setButtonText("Rename").onClick(() => this.prompt("Rename profile", profile.name, async (name) => { profile.name = name; await this.saveRefresh(); }))).addButton((b) => b.setButtonText("Duplicate").onClick(async () => { const copy = duplicateProfile(profile); this.plugin.settings.profiles.push(copy); this.plugin.settings.activeProfileId = copy.id; await this.saveRefresh(); })).addButton((b) => b.setButtonText("Delete").setWarning().onClick(async () => { if (this.plugin.settings.profiles.length === 1) { new Notice("At least one profile is required."); return; } this.plugin.settings.profiles = this.plugin.settings.profiles.filter((item) => item.id !== profile.id); this.plugin.settings.activeProfileId = this.plugin.settings.profiles[0].id; if (this.plugin.settings.defaultProfileId === profile.id) this.plugin.settings.defaultProfileId = this.plugin.settings.profiles[0].id; await this.saveRefresh(); }));
    new Setting(c).setName("Profile JSON").addButton((b) => b.setButtonText("Export").onClick(() => new ProfileJsonModal(this.app, "export", profile, () => undefined).open())).addButton((b) => b.setButtonText("Import").onClick(() => new ProfileJsonModal(this.app, "import", profile, (json) => { if (json) void this.importProfile(json); }).open())).addButton((b) => b.setButtonText("Restore defaults").onClick(async () => { const defaults = createDefaultProfiles(); this.plugin.settings.profiles = defaults; this.plugin.settings.activeProfileId = defaults[0].id; this.plugin.settings.defaultProfileId = defaults[0].id; await this.saveRefresh(); }));
    new Setting(c).setName("Default profile").addDropdown((dropdown) => { this.plugin.settings.profiles.forEach((item) => dropdown.addOption(item.id, item.name)); dropdown.setValue(this.plugin.settings.defaultProfileId).onChange(async (id) => { this.plugin.settings.defaultProfileId = id; await this.plugin.saveSettings(); }); });
    c.createEl("h3", { text: "Profile destinations" }); this.text(c, profile, "Manuscript root", "manuscriptRoot", "Books/My Book"); this.text(c, profile, "Export folder", "exportFolder", "Manuscript Exports"); this.text(c, profile, "Output filename", "outputFilename", "{BookTitle} Manuscript.md");
    new Setting(c).setName("Export target").addDropdown((d) => d.addOption("markdown", "Markdown").addOption("docx", "DOCX").addOption("markdown-docx", "Markdown + DOCX").setValue(profile.exportTarget).onChange(async (value) => { profile.exportTarget = value === "docx" ? "docx" : value === "markdown-docx" ? "markdown-docx" : "markdown"; await this.plugin.saveSettings(); }));
    this.pathSetting(c, profile, "Reference DOCX", "referenceDocx", "Optional reference DOCX template.", ".docx"); this.pathSetting(c, profile, "Pandoc metadata file", "pandocMetadataFile", "Optional YAML or JSON metadata file.", ".yaml,.yml,.json");
    this.text(c, profile, "Additional Pandoc arguments", "additionalPandocArguments", "--number-sections"); this.toggle(c, profile, "Generate table of contents", "generateTableOfContents"); this.toggle(c, profile, "Keep intermediate Markdown", "keepIntermediateMarkdown");
    c.createEl("h3", { text: "Variables" }); this.variable(c, profile, "Book title", "BookTitle"); this.variable(c, profile, "Series", "Series"); this.variable(c, profile, "Author", "Author");
    c.createEl("h3", { text: "Structure" }); this.toggle(c, profile, "Include front matter", "includeFrontMatter"); this.toggle(c, profile, "Include back matter", "includeBackMatter"); this.toggle(c, profile, "Include scene titles", "includeSceneTitles"); this.text(c, profile, "Part heading template", "partHeadingTemplate", "Part {number}: {name}"); this.text(c, profile, "Chapter heading template", "chapterHeadingTemplate", "Chapter {number}: {name}"); this.text(c, profile, "Scene separator", "sceneSeparator", "#"); this.number(c, profile, "Blank lines between sections", "blankLinesBetweenSections", 0, 5); this.number(c, profile, "Blank lines before chapters", "blankLinesBetweenChapters", 0, 5);
    new Setting(c).setName("Ordering method").addDropdown((d) => d.addOption("filename", "Filename").addOption("metadata", "Metadata").setValue(profile.orderingMethod).onChange(async (value) => { profile.orderingMethod = value === "metadata" ? "metadata" : "filename"; profile.metadataOrdering = profile.orderingMethod === "metadata"; await this.plugin.saveSettings(); }));
    c.createEl("h3", { text: "Content cleaning" }); for (const [name, key] of [["Strip YAML frontmatter", "stripYamlFrontmatter"], ["Remove Obsidian comments", "removeObsidianComments"], ["Remove HTML comments", "removeHtmlComments"], ["Remove Dataview blocks", "removeDataviewBlocks"], ["Remove callouts", "removeCallouts"], ["Strip internal links", "stripInternalLinks"]] as const) this.toggle(c, profile, name, key);
    c.createEl("h3", { text: "Metadata filters" }); profile.metadataFilters.forEach((rule) => this.filterRow(c, profile, rule)); new Setting(c).addButton((b) => b.setButtonText("Add filter").onClick(async () => { profile.metadataFilters.push({ id: profileId(), field: "Editing Status", operator: "not-equals", value: "Excluded" }); await this.saveRefresh(); }));
    c.createEl("h3", { text: "Pandoc and export defaults" }); new Setting(c).setName("Pandoc executable path").setDesc("Leave blank to use automatic detection.").addText((t) => t.setPlaceholder("/usr/local/bin/pandoc").setValue(this.plugin.settings.pandocExecutablePath).onChange(async (value) => { this.plugin.settings.pandocExecutablePath = value.trim(); await this.plugin.saveSettings(); })).addButton((b) => b.setButtonText("Detect").onClick(async () => { const status = await this.plugin.detectPandoc(); new Notice(status.available ? `Pandoc ${status.version ?? "detected"} at ${status.executable}` : status.explanation ?? "Pandoc unavailable", 8000); })); this.globalToggle(c, "Automatically detect Pandoc", "automaticallyDetectPandoc"); new Setting(c).setName("Default export format").addDropdown((d) => d.addOption("markdown", "Markdown").addOption("docx", "DOCX").addOption("markdown-docx", "Markdown + DOCX").setValue(this.plugin.settings.defaultExportFormat).onChange(async (value) => { this.plugin.settings.defaultExportFormat = value === "docx" ? "docx" : value === "markdown-docx" ? "markdown-docx" : "markdown"; await this.plugin.saveSettings(); })); new Setting(c).setName("Default reference DOCX").addText((t) => t.setValue(this.plugin.settings.defaultReferenceDocx).onChange(async (value) => { this.plugin.settings.defaultReferenceDocx = value.trim(); await this.plugin.saveSettings(); })); this.globalToggle(c, "Keep temporary Markdown", "keepTemporaryMarkdown"); this.globalToggle(c, "Enable compile logs", "enableCompileLogs"); new Setting(c).setName("Maximum export history entries").addText((t) => t.setValue(String(this.plugin.settings.maximumExportHistoryEntries)).onChange(async (value) => { const parsed = Number(value); if (Number.isInteger(parsed) && parsed > 0) { this.plugin.settings.maximumExportHistoryEntries = parsed; await this.plugin.saveSettings(); } })); new Setting(c).setName("Export records").addButton((b) => b.setButtonText(`History (${this.plugin.settings.exportHistory.length})`).onClick(() => new ExportHistoryModal(this.app, this.plugin).open())).addButton((b) => b.setButtonText(`Logs (${this.plugin.settings.compileLogs.length})`).onClick(() => new CompileLogsModal(this.app, this.plugin).open()));
    c.createEl("h3", { text: "Preview and reporting" }); this.globalToggle(c, "Show compile preview", "showPreview"); this.globalToggle(c, "Expand preview tree", "expandPreviewTree"); this.globalToggle(c, "Show statistics", "showStatistics"); new Setting(c).setName("Minimum warning level").addDropdown((d) => d.addOption("information", "Information").addOption("warning", "Warning").addOption("error", "Error").setValue(this.plugin.settings.minimumWarningLevel).onChange(async (value) => { this.plugin.settings.minimumWarningLevel = value as WarningLevel; await this.plugin.saveSettings(); })); new Setting(c).setName("Reading speed").setDesc("Words per minute used for reading-time estimates.").addText((t) => t.setValue(String(this.plugin.settings.readingWordsPerMinute)).onChange(async (value) => { const parsed = Number(value); if (Number.isFinite(parsed) && parsed > 0) { this.plugin.settings.readingWordsPerMinute = parsed; await this.plugin.saveSettings(); } })); if (this.plugin.settings.configurationWarnings.length) { const repairs = c.createEl("details"); repairs.createEl("summary", { text: `Configuration repair history (${this.plugin.settings.configurationWarnings.length})` }); const list = repairs.createEl("ul"); this.plugin.settings.configurationWarnings.forEach((warning) => list.createEl("li", { text: warning })); }
  }
  private text(c: HTMLElement, p: CompileProfile, name: string, key: "manuscriptRoot" | "exportFolder" | "outputFilename" | "partHeadingTemplate" | "chapterHeadingTemplate" | "sceneSeparator" | "additionalPandocArguments", placeholder: string): void { new Setting(c).setName(name).addText((t) => t.setPlaceholder(placeholder).setValue(p[key]).onChange(async (value) => { p[key] = value.trim(); await this.plugin.saveSettings(); })); }
  private variable(c: HTMLElement, p: CompileProfile, name: string, key: keyof CompileProfile["variables"]): void { new Setting(c).setName(name).addText((t) => t.setValue(p.variables[key]).onChange(async (value) => { p.variables[key] = value.trim(); await this.plugin.saveSettings(); })); }
  private toggle(c: HTMLElement, p: CompileProfile, name: string, key: "includeFrontMatter" | "includeBackMatter" | "includeSceneTitles" | "stripYamlFrontmatter" | "removeObsidianComments" | "removeHtmlComments" | "removeDataviewBlocks" | "removeCallouts" | "stripInternalLinks" | "generateTableOfContents" | "keepIntermediateMarkdown"): void { new Setting(c).setName(name).addToggle((t) => t.setValue(p[key]).onChange(async (value) => { p[key] = value; await this.plugin.saveSettings(); })); }
  private globalToggle(c: HTMLElement, name: string, key: "showPreview" | "expandPreviewTree" | "showStatistics" | "automaticallyDetectPandoc" | "keepTemporaryMarkdown" | "enableCompileLogs"): void { new Setting(c).setName(name).addToggle((t) => t.setValue(this.plugin.settings[key]).onChange(async (value) => { this.plugin.settings[key] = value; await this.plugin.saveSettings(); })); }
  private pathSetting(c: HTMLElement, p: CompileProfile, name: string, key: "referenceDocx" | "pandocMetadataFile", description: string, accept: string): void { const setting = new Setting(c).setName(name).setDesc(description); setting.addText((t) => t.setValue(p[key]).onChange(async (value) => { p[key] = value.trim(); await this.plugin.saveSettings(); })); setting.addButton((button) => button.setButtonText("Browse").onClick(() => chooseLocalFile(accept, (path) => { p[key] = path; void this.saveRefresh(); }))); }
  private number(c: HTMLElement, p: CompileProfile, name: string, key: "blankLinesBetweenSections" | "blankLinesBetweenChapters", min: number, max: number): void { new Setting(c).setName(name).addSlider((s) => s.setLimits(min, max, 1).setDynamicTooltip().setValue(p[key]).onChange(async (value) => { p[key] = value; await this.plugin.saveSettings(); })); }
  private filterRow(c: HTMLElement, p: CompileProfile, rule: MetadataFilterRule): void { new Setting(c).setName("Filter rule").addText((t) => t.setPlaceholder("POV").setValue(rule.field).onChange(async (value) => { rule.field = value.trim(); await this.plugin.saveSettings(); })).addDropdown((d) => d.addOption("equals", "equals").addOption("not-equals", "does not equal").setValue(rule.operator).onChange(async (value) => { rule.operator = value === "equals" ? "equals" : "not-equals"; await this.plugin.saveSettings(); })).addText((t) => t.setPlaceholder("Elin").setValue(rule.value).onChange(async (value) => { rule.value = value; await this.plugin.saveSettings(); })).addExtraButton((b) => b.setIcon("trash").setTooltip("Remove filter").onClick(async () => { p.metadataFilters = p.metadataFilters.filter((item) => item.id !== rule.id); await this.saveRefresh(); })); }
  private prompt(title: string, initial: string, action: (value: string) => Promise<void>): void { new TextPromptModal(this.app, title, initial, (value) => { if (value) void action(value); }).open(); }
  private async importProfile(json: string): Promise<void> { try { const result = validateProfile(JSON.parse(json)); if (!result.profile) { new Notice(`Invalid profile: ${result.errors.join(" ")}`, 8000); return; } this.plugin.settings.profiles.push(result.profile); this.plugin.settings.activeProfileId = result.profile.id; await this.saveRefresh(); } catch (error) { new Notice(`Invalid JSON: ${error instanceof Error ? error.message : String(error)}`, 8000); } }
  private async saveRefresh(): Promise<void> { await this.plugin.saveSettings(); this.display(); }
}
export function showError(error: unknown): void { const message = error instanceof Error ? error.message : String(error); new Notice(`Manuscript Compiler: ${message}`, 8000); console.error("Manuscript Compiler", error); }
